/**
 * ============================================================================
 * PARMCO — Phone APP RP4 Motor Control — BLE GATT Server
 * ============================================================================
 *
 * File:        ble_server.c
 * Project:     PARMCO (Phone APP RP4 Motor Control)
 * Course:      ECSE 4235 — Embedded Systems, Spring 2026
 * University:  University of Georgia
 * Authors:     Justin Moreno and Jalen Edusei
 * Date:        April 1, 2026
 * Checkpoint:  3 — BLE Peripheral with GATT service and pairing agent
 *
 * Description:
 *   This program turns the Raspberry Pi 4 into a Bluetooth Low Energy
 *   Peripheral device. It registers a custom GATT service with BlueZ via
 *   the D-Bus system bus, advertises the service UUID so the PARMCO phone
 *   app can discover and connect, and processes motor control commands
 *   received over BLE.
 *
 *   CRITICAL FIX (CP3): Registers a NoInputNoOutput pairing agent with
 *   BlueZ via D-Bus. Without an agent, when iOS initiates a BLE connection
 *   and BlueZ triggers pairing (either from "write" characteristic flags
 *   or from BlueZ's automatic service caching behavior), the pairing
 *   request has no handler. BlueZ prints "Waiting for response from
 *   Bluetooth device" and eventually times out, leaving the iPhone stuck.
 *   The NoInputNoOutput agent automatically accepts all pairing requests
 *   with "Just Works" pairing — no PIN, no passkey, no user interaction.
 *   This is appropriate for PARMCO because the system does not transmit
 *   sensitive data and operates in a controlled lab environment.
 *
 *   Additionally, the command characteristic now includes the
 *   "write-without-response" flag alongside "write". This allows iOS to
 *   use the faster ATT Write Without Response path, which does not require
 *   an authenticated link and avoids triggering unnecessary SMP pairing
 *   exchanges for simple motor commands.
 *
 *   For Checkpoint 2, the telemetry characteristic sends a mock RPM value
 *   derived from the current speed percentage. Real sensor-based RPM
 *   measurement will be integrated in Checkpoint 3.
 *
 * AI Attribution:
 *   This code was AI-Generated by Claude Opus 4.6 (Anthropic) on March 25, 2026.
 *   Prompt engineering and validation by Justin Moreno and Jalen Edusei.
 *
 * ============================================================================
 * LIBRARY ATTRIBUTION — GLib 2.0 / GIO / GDBus
 * ============================================================================
 *
 *   This program uses GLib 2.0 and its GIO module (specifically GDBus) to
 *   communicate with the BlueZ Bluetooth daemon over D-Bus IPC.
 *
 *   Origin:
 *     GLib is part of the GNOME project, maintained by the GNOME Foundation.
 *     https://docs.gtk.org/glib/
 *     GIO/GDBus documentation: https://docs.gtk.org/gio/
 *
 *   Role in this program:
 *     BlueZ (the Linux Bluetooth protocol stack) exposes its BLE GATT and
 *     advertising APIs exclusively through D-Bus, a system-level inter-process
 *     communication bus. To create a BLE peripheral, a user-space application
 *     must publish a hierarchy of D-Bus objects implementing BlueZ's defined
 *     interfaces (org.bluez.GattService1, org.bluez.GattCharacteristic1,
 *     org.bluez.LEAdvertisement1, etc.) and then call registration methods
 *     on BlueZ's adapter objects.
 *
 *     Writing raw D-Bus protocol handling in C is extremely tedious and
 *     error-prone — it involves manual construction of D-Bus message
 *     variants, complex type signature strings ("a{sv}", "ao", etc.),
 *     and careful reference-counted memory management. GDBus (the D-Bus
 *     implementation built into GLib's GIO module) abstracts this into a
 *     clean C API using GVariant for type-safe message construction,
 *     GDBusConnection for bus access, and XML introspection data for
 *     automatic interface skeleton generation.
 *
 *   Why it is necessary:
 *     Without GDBus (or a similar abstraction like sd-bus or dbus-glib),
 *     implementing a BlueZ GATT server would require approximately 3-5x
 *     more code, all of it dealing with low-level D-Bus wire protocol
 *     details rather than application logic. GLib also provides the main
 *     event loop (GMainLoop) that BlueZ requires for asynchronous signal
 *     delivery and method call dispatch.
 *
 *   Installation on Raspberry Pi OS:
 *     sudo apt install libglib2.0-dev
 *
 * ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdint.h>
#include <sys/mman.h>

#include <gio/gio.h>
#include <glib.h>

/* === HUMAN EDIT START (CP3 Phase 0, Jalen) ===
 * pigpio gives us hardware PWM on GPIO18 and clean edge-detect callbacks
 * on the IR sensor GPIO17. Without merging this in, the BLE server just
 * mutates a struct and prints log lines — the motor never moves. The
 * GPIO helpers below come from ../motor/gpio_asm.o (ARMv8 assembly).
 */
#include <pigpio.h>

extern void gpio_init(volatile void *base_ptr);
extern void gpio_set_output(unsigned int pin);
extern void gpio_write(unsigned int pin, unsigned int value);
/* === HUMAN EDIT END === */

/* ============================================================================
 * UUID DEFINITIONS
 * ============================================================================
 * Custom 128-bit UUIDs for the PARMCO BLE service. These must match exactly
 * on the phone app side (BLEManager.ts) for service discovery to succeed.
 */
#define PARMCO_SERVICE_UUID     "12345678-1234-5678-1234-56789abcdef0"
#define COMMAND_CHAR_UUID       "12345678-1234-5678-1234-56789abcdef1"
#define TELEMETRY_CHAR_UUID     "12345678-1234-5678-1234-56789abcdef2"

/* D-Bus object paths — BlueZ requires a hierarchical object tree:
 *   /com/parmco              → the GATT Application root
 *   /com/parmco/service0     → the primary GATT service
 *   /com/parmco/service0/cmd → the command characteristic
 *   /com/parmco/service0/tel → the telemetry characteristic
 *   /com/parmco/adv0         → the LE advertisement
 */
#define APP_PATH        "/com/parmco"
#define SERVICE_PATH    "/com/parmco/service0"
#define CMD_CHAR_PATH   "/com/parmco/service0/cmd"
#define TEL_CHAR_PATH   "/com/parmco/service0/tel"
#define ADV_PATH        "/com/parmco/adv0"

/* BlueZ D-Bus service name and standard interface names */
#define BLUEZ_BUS_NAME              "org.bluez"
#define ADAPTER_PATH                "/org/bluez/hci0"
#define GATT_MANAGER_IFACE          "org.bluez.GattManager1"
#define LE_ADV_MANAGER_IFACE        "org.bluez.LEAdvertisingManager1"
#define AGENT_MANAGER_IFACE         "org.bluez.AgentManager1"
#define PROPERTIES_IFACE            "org.freedesktop.DBus.Properties"
#define OBJECT_MANAGER_IFACE        "org.freedesktop.DBus.ObjectManager"

/* Pairing agent D-Bus path and capability.
 *
 * WHY THIS IS NEEDED:
 *   BlueZ requires a registered "agent" to handle pairing requests. The
 *   agent is a D-Bus object that implements org.bluez.Agent1 and responds
 *   to methods like RequestConfirmation, RequestPasskey, AuthorizeService,
 *   etc. When iOS connects to the RP4 and BlueZ initiates pairing (either
 *   because a characteristic has "write" flags that BlueZ interprets as
 *   requiring authentication, or because iOS probes standard GATT services
 *   that trigger an SMP exchange), BlueZ dispatches the pairing request
 *   to whatever agent is registered.
 *
 *   If NO agent is registered, BlueZ has nobody to ask, so it queues the
 *   pairing request and waits for an agent to appear. This produces the
 *   "Waiting for response from Bluetooth device" hang on the RP4 side,
 *   and a pairing timeout on the iPhone side.
 *
 *   The "NoInputNoOutput" capability tells BlueZ that this device has no
 *   keyboard, no display, and no way to show or enter a PIN. BlueZ then
 *   uses "Just Works" pairing (BLE Secure Connections with no MITM
 *   protection). The agent's RequestConfirmation handler simply returns
 *   success immediately, auto-accepting all pairing requests.
 */
#define AGENT_PATH                  "/com/parmco/agent"
#define AGENT_CAPABILITY            "NoInputNoOutput"

/* Telemetry update interval in milliseconds.
 * CP3 spec demands 5 Hz while running and 1 Hz while idle; we use a 200 ms
 * base tick and skip 4 of every 5 ticks when the motor is stopped. */
#define TELEMETRY_INTERVAL_MS       200

/* === HUMAN EDIT START (Final, Jalen) ===
 * Control-mode enum hoisted up here because MotorState now carries
 * a `mode` field. Full commentary on each mode lives in the hardware
 * layer block below where the controller constants are defined. */
typedef enum {
    MODE_MANUAL   = 0,
    MODE_MAINTAIN = 1,
    MODE_MATCH    = 2
} control_mode_t;
/* === HUMAN EDIT END === */

/* ============================================================================
 * MOTOR STATE — Global variables shared with the motor control module
 * ============================================================================
 * These represent the logical state of the motor as commanded by the phone.
 * In CP3, these will be read by the motor control loop (motor_control.c)
 * to drive the actual hardware via GPIO/PWM.
 */
typedef struct {
    char direction[8];  /* "FWD" or "REV" */
    int  speed;         /* 0–100 (duty cycle percentage, canonical in MANUAL mode) */
    int  running;       /* 1 = motor on, 0 = motor off */
    int  rpm;           /* Live RPM from the motor's own IR sensor */
    int  target_rpm;    /* Setpoint for MAINTAIN mode */
    /* === HUMAN EDIT START (Final, Jalen) ===
     * Final-project additions — everything the phone can select or
     * read back over BLE lives on this one struct so telemetry and
     * command handlers have a single source of truth. */
    control_mode_t mode;       /* MANUAL / MAINTAIN / MATCH */
    int            ref_rpm;    /* Reference RPM measured on GPIO23 (MATCH setpoint) */
    int            pwm_duty;   /* Current raw 0-255 duty the controller has settled on */
    /* === HUMAN EDIT END === */
} MotorState;

static MotorState motor_state = {
    .direction  = "FWD",
    .speed      = 0,
    .running    = 0,
    .rpm        = 0,
    .target_rpm = 0,
    /* === HUMAN EDIT START (Final, Jalen) === */
    .mode       = MODE_MANUAL,
    .ref_rpm    = 0,
    .pwm_duty   = 0
    /* === HUMAN EDIT END === */
};

/* === HUMAN EDIT START (CP3 Phase 0, Jalen) ===
 * Motor hardware layer merged in from motor/motor_control_cp3.c. Until
 * CP3 the motor daemon ran as a separate keyboard-driven program — BLE
 * commands never reached a GPIO. Now parse_command() calls motor_hw_apply()
 * and the telemetry callback reads real IR-sensor RPM via motor_hw_sample_rpm().
 */
#define PIN_ENABLE       18   /* L293D EN1 — hardware PWM */
#define PIN_IN1          20   /* L293D IN1 — direction bit A */
#define PIN_IN2          21   /* L293D IN2 — direction bit B */
#define PIN_IR           17   /* 74HC374-latched IR tach edge (motor propeller) */
#define PIN_IR_REF       23   /* second IR sensor / function generator (Match mode reference) */
#define PWM_MAX_DUTY     255
#define PULSES_PER_REV   3    /* three propeller flaps per revolution (same on both sensors) */
#define RPM_WINDOW_MS    500  /* sliding window for edge counting */
#define MIN_PULSE_US     1000 /* reject bounce closer than this */
#define GPIO_PHYS_BASE   0xFE200000UL  /* BCM2711 GPIO base */
#define GPIO_MAP_SIZE    0x1000

/* === HUMAN EDIT START (Final, Jalen) ===
 * Control-mode plumbing pulled in from motor/motor_control_cp3.c so the
 * BLE server can run the closed-loop controllers directly — there is no
 * longer a separate keypad daemon to own the GPIOs. Three modes:
 *
 *   MANUAL    — phone's SPD:<0-100> pushes straight to PWM. No feedback.
 *   MAINTAIN  — phone's RPM:<target> is held using the motor's own IR
 *               tach as feedback. Proportional controller, Kp tuned on
 *               the bench so 4500 RPM target settles within ~1 sec.
 *   MATCH     — motor tracks whatever is turning on GPIO23 (the second
 *               IR sensor or a bench function generator). Uses ref_rpm
 *               as the setpoint instead of a phone-supplied number.
 *
 * The gain, deadband, and sampling period constants mirror the keypad
 * build so behaviour is identical whether the user drives the motor
 * from the app or from a console ssh session.
 *
 * (The enum itself was hoisted above MotorState — see the definition
 * near the top of the file. Only the numeric tuning constants live here.)
 */
#define CONTROL_PERIOD_MS   250      /* controller tick rate */
#define KP                  0.04f    /* proportional gain, duty-counts per RPM error */
#define CONTROL_DEADBAND    30.0f    /* +/- RPM inside which we stop chasing */
#define TARGET_RPM_MIN      0
#define TARGET_RPM_MAX      6000
/* === HUMAN EDIT END === */

static volatile void *gpio_base_map = NULL;
static int            motor_hw_ready = 0;

/* IR edge state — updated from a pigpio alert callback */
static volatile unsigned int ir_pulse_count = 0;
static volatile uint32_t     ir_last_tick   = 0;

/* === HUMAN EDIT START (Final, Jalen) ===
 * Reference IR state lives alongside the primary tach state. Same
 * debounce rule, same edge polarity, different pin. Volatile because
 * the pigpio alert thread touches these asynchronously to the main
 * GLib loop. */
static volatile unsigned int ref_pulse_count = 0;
static volatile uint32_t     ref_last_tick   = 0;
/* === HUMAN EDIT END === */

static void ir_edge_cb(int gpio, int level, uint32_t tick)
{
    (void)gpio;
    /* falling edge only, with bounce filter */
    if (level != 0) return;
    if (ir_last_tick != 0 && (tick - ir_last_tick) < MIN_PULSE_US) return;
    ir_last_tick = tick;
    ir_pulse_count++;
}

/* === HUMAN EDIT START (Final, Jalen) ===
 * Reference IR callback. Mirrors ir_edge_cb exactly. Separate function
 * because pigpio wants one callback per pin — we can't multiplex. */
static void ref_ir_edge_cb(int gpio, int level, uint32_t tick)
{
    (void)gpio;
    if (level != 0) return;
    if (ref_last_tick != 0 && (tick - ref_last_tick) < MIN_PULSE_US) return;
    ref_last_tick = tick;
    ref_pulse_count++;
}
/* === HUMAN EDIT END === */

static int motor_hw_init(void)
{
    /* Map /dev/gpiomem for the asm helpers (pigpio owns its own mapping) */
    int fd = open("/dev/gpiomem", O_RDWR | O_SYNC);
    if (fd < 0) {
        fprintf(stderr, "[PARMCO] open(/dev/gpiomem) failed — run as root?\n");
        return -1;
    }
    gpio_base_map = mmap(NULL, GPIO_MAP_SIZE, PROT_READ | PROT_WRITE,
                         MAP_SHARED, fd, 0);
    close(fd);
    if (gpio_base_map == MAP_FAILED) {
        fprintf(stderr, "[PARMCO] mmap gpiomem failed\n");
        gpio_base_map = NULL;
        return -1;
    }
    gpio_init(gpio_base_map);

    if (gpioInitialise() < 0) {
        fprintf(stderr, "[PARMCO] gpioInitialise() failed\n");
        return -1;
    }

    /* Direction pins — pigpio owns them so bluez coexistence is clean */
    gpioSetMode(PIN_IN1, PI_OUTPUT);
    gpioSetMode(PIN_IN2, PI_OUTPUT);
    gpioWrite(PIN_IN1, 0);
    gpioWrite(PIN_IN2, 0);

    /* PWM on EN1 — 8-bit range, 1 kHz carrier for the L293D */
    gpioSetMode(PIN_ENABLE, PI_OUTPUT);
    gpioSetPWMrange(PIN_ENABLE, PWM_MAX_DUTY);
    gpioSetPWMfrequency(PIN_ENABLE, 1000);
    gpioPWM(PIN_ENABLE, 0);

    /* IR sensor — pull-up, falling-edge callback */
    gpioSetMode(PIN_IR, PI_INPUT);
    gpioSetPullUpDown(PIN_IR, PI_PUD_UP);
    gpioSetAlertFunc(PIN_IR, ir_edge_cb);

    /* === HUMAN EDIT START (Final, Jalen) ===
     * Reference IR sensor on GPIO23. Pull is set to OFF so an external
     * function generator can drive it without fighting the internal
     * resistor — if a real second IR phototransistor is used instead
     * it provides its own pull-up through the 74HC374 latch. Same
     * bounce filter as the primary via the shared MIN_PULSE_US. */
    gpioSetMode(PIN_IR_REF, PI_INPUT);
    gpioSetPullUpDown(PIN_IR_REF, PI_PUD_OFF);
    gpioSetAlertFunc(PIN_IR_REF, ref_ir_edge_cb);
    /* === HUMAN EDIT END === */

    motor_hw_ready = 1;
    printf("[PARMCO] Motor HW init OK — EN=%d IN1=%d IN2=%d IR=%d IR_REF=%d\n",
           PIN_ENABLE, PIN_IN1, PIN_IN2, PIN_IR, PIN_IR_REF);
    return 0;
}

static void motor_hw_shutdown(void)
{
    if (!motor_hw_ready) return;
    gpioPWM(PIN_ENABLE, 0);
    gpioWrite(PIN_IN1, 0);
    gpioWrite(PIN_IN2, 0);
    gpioSetAlertFunc(PIN_IR, NULL);
    /* === HUMAN EDIT START (Final, Jalen) === */
    gpioSetAlertFunc(PIN_IR_REF, NULL);
    /* === HUMAN EDIT END === */
    gpioTerminate();
    if (gpio_base_map && gpio_base_map != MAP_FAILED) {
        munmap((void *)gpio_base_map, GPIO_MAP_SIZE);
        gpio_base_map = NULL;
    }
    motor_hw_ready = 0;
}

/* Drive the pins to match motor_state. Called from parse_command() whenever
 * a value that affects the output stage has changed.
 *
 * === HUMAN EDIT (Final, Jalen) ===
 * Expanded for mode awareness:
 *   - MANUAL: PWM comes straight from motor_state.speed. This function
 *     writes it.
 *   - MAINTAIN / MATCH: the controller thread owns PWM. This function
 *     only handles direction pins and the running/stopped gate. It
 *     seeds pwm_duty from speed on START so the controller has a
 *     reasonable starting point instead of ramping up from zero.
 */
static void motor_hw_apply(void)
{
    if (!motor_hw_ready) return;

    if (!motor_state.running) {
        gpioPWM(PIN_ENABLE, 0);
        gpioWrite(PIN_IN1, 0);
        gpioWrite(PIN_IN2, 0);
        motor_state.pwm_duty = 0;
        return;
    }

    if (strcmp(motor_state.direction, "FWD") == 0) {
        gpioWrite(PIN_IN1, 1);
        gpioWrite(PIN_IN2, 0);
    } else {
        gpioWrite(PIN_IN1, 0);
        gpioWrite(PIN_IN2, 1);
    }

    if (motor_state.mode == MODE_MANUAL) {
        /* Direct passthrough. speed is 0-100, scale to 0-255. */
        int duty = (motor_state.speed * PWM_MAX_DUTY) / 100;
        if (duty < 0) duty = 0;
        if (duty > PWM_MAX_DUTY) duty = PWM_MAX_DUTY;
        motor_state.pwm_duty = duty;
        gpioPWM(PIN_ENABLE, duty);
    } else {
        /* Auto mode. Seed pwm_duty from speed if the controller hasn't
         * spun up yet, so START doesn't crater to 0 while the loop
         * waits for its first tick. Once pwm_duty is nonzero the
         * controller takes over. */
        if (motor_state.pwm_duty == 0) {
            int seed = (motor_state.speed * PWM_MAX_DUTY) / 100;
            if (seed < 30) seed = 30;       /* stiction floor */
            if (seed > PWM_MAX_DUTY) seed = PWM_MAX_DUTY;
            motor_state.pwm_duty = seed;
        }
        gpioPWM(PIN_ENABLE, motor_state.pwm_duty);
    }
}

/* Snapshot the IR edge counter and compute RPM over RPM_WINDOW_MS. */
static int motor_hw_sample_rpm(void)
{
    static uint32_t window_start_tick = 0;
    static unsigned int last_count = 0;
    static int cached_rpm = 0;

    if (!motor_hw_ready) return 0;

    uint32_t now = gpioTick();
    unsigned int count_now = ir_pulse_count;

    if (window_start_tick == 0) {
        window_start_tick = now;
        last_count = count_now;
        return 0;
    }

    uint32_t elapsed_us = now - window_start_tick;
    if (elapsed_us < (RPM_WINDOW_MS * 1000u)) {
        return cached_rpm;
    }

    unsigned int pulses = count_now - last_count;
    /* rpm = pulses per minute / pulses per rev */
    cached_rpm = (int)((pulses * 60000000ull) /
                       ((uint64_t)elapsed_us * PULSES_PER_REV));
    window_start_tick = now;
    last_count = count_now;
    return cached_rpm;
}
/* === HUMAN EDIT END === */

/* === HUMAN EDIT START (Final, Jalen) ===
 * Reference RPM sampler. Identical to motor_hw_sample_rpm but bound to
 * the GPIO23 pulse counter. Kept as a separate function (rather than
 * parameterising the existing one) so each sensor carries its own
 * sliding-window state — the two pulse streams run at independent
 * rates and sharing static state would desync them. */
static int motor_hw_sample_ref_rpm(void)
{
    static uint32_t window_start_tick = 0;
    static unsigned int last_count = 0;
    static int cached_rpm = 0;

    if (!motor_hw_ready) return 0;

    uint32_t now = gpioTick();
    unsigned int count_now = ref_pulse_count;

    if (window_start_tick == 0) {
        window_start_tick = now;
        last_count = count_now;
        return 0;
    }

    uint32_t elapsed_us = now - window_start_tick;
    if (elapsed_us < (RPM_WINDOW_MS * 1000u)) {
        return cached_rpm;
    }

    unsigned int pulses = count_now - last_count;
    cached_rpm = (int)((pulses * 60000000ull) /
                       ((uint64_t)elapsed_us * PULSES_PER_REV));
    window_start_tick = now;
    last_count = count_now;
    return cached_rpm;
}

/* ============================================================================
 * CONTROLLERS
 * ============================================================================
 * Both auto modes are P-only — proportional gain alone. An integral term
 * is tempting but the mechanical load here (small 12V DC motor with a
 * 3-flap propeller) has enough damping that I-windup causes worse
 * oscillation than it fixes. Kp = 0.04 duty-counts per RPM error was
 * tuned on the bench: target 4500 RPM settles within ~1 second with
 * no visible overshoot.
 *
 * Deadband of ±30 RPM keeps the controller from thrashing the PWM on
 * tach quantisation noise. Below that error threshold we hold duty
 * constant and accept the offset.
 *
 * Both controllers clamp pwm_duty to [0, PWM_MAX_DUTY]. Going below 0
 * would be meaningless (no reverse-drive through PWM on L293D EN) and
 * going above 255 is an unsigned wrap waiting to happen.
 */

/* MAINTAIN: hold motor_state.rpm at motor_state.target_rpm using the
 * primary IR sensor as feedback. */
static void update_maintain_mode(void)
{
    if (!motor_hw_ready || !motor_state.running) return;

    float error  = (float)motor_state.target_rpm - (float)motor_state.rpm;
    int   adjust = (int)(KP * error);

    if (error > -CONTROL_DEADBAND && error < CONTROL_DEADBAND) {
        adjust = 0;
    }

    int new_duty = motor_state.pwm_duty + adjust;
    if (new_duty < 0)             new_duty = 0;
    if (new_duty > PWM_MAX_DUTY)  new_duty = PWM_MAX_DUTY;

    motor_state.pwm_duty = new_duty;
    gpioPWM(PIN_ENABLE, new_duty);
}

/* MATCH: hold motor_state.rpm at motor_state.ref_rpm — the reference
 * being whatever is turning on GPIO23. If nothing is present on the
 * reference channel (ref_rpm == 0), coast the motor down rather than
 * driving it to zero abruptly, which is friendlier to the driver IC. */
static void update_match_mode(void)
{
    if (!motor_hw_ready || !motor_state.running) return;

    /* No reference signal — just hold whatever we're doing. */
    if (motor_state.ref_rpm <= 0) {
        gpioPWM(PIN_ENABLE, motor_state.pwm_duty);
        return;
    }

    float error  = (float)motor_state.ref_rpm - (float)motor_state.rpm;
    int   adjust = (int)(KP * error);

    if (error > -CONTROL_DEADBAND && error < CONTROL_DEADBAND) {
        adjust = 0;
    }

    int new_duty = motor_state.pwm_duty + adjust;
    if (new_duty < 0)             new_duty = 0;
    if (new_duty > PWM_MAX_DUTY)  new_duty = PWM_MAX_DUTY;

    motor_state.pwm_duty = new_duty;
    gpioPWM(PIN_ENABLE, new_duty);
}
/* === HUMAN EDIT END === */

/* ============================================================================
 * GLOBAL HANDLES
 * ============================================================================ */
static GMainLoop       *main_loop = NULL;       /* GLib event loop */
static GDBusConnection *dbus_conn = NULL;        /* System D-Bus connection */
static guint            app_reg_id = 0;          /* ObjectManager registration */
static guint            svc_reg_id = 0;          /* Service object registration */
static guint            cmd_reg_id = 0;          /* Command char registration */
static guint            tel_reg_id = 0;          /* Telemetry char registration */
static guint            adv_reg_id = 0;          /* Advertisement registration */
static guint            agent_reg_id = 0;        /* Pairing agent registration */
static guint            telemetry_timer_id = 0;  /* Periodic telemetry source */
/* === HUMAN EDIT START (Final, Jalen) === */
static guint            controller_timer_id = 0; /* Periodic MAINTAIN/MATCH tick */
/* === HUMAN EDIT END === */

/* ============================================================================
 * D-BUS INTROSPECTION XML
 * ============================================================================
 * BlueZ expects each GATT object to implement specific D-Bus interfaces.
 * GDBus uses XML introspection data to automatically handle method dispatch,
 * property access, and signal emission. Each XML block below defines the
 * interface that the corresponding D-Bus object exposes.
 */

/* --- ObjectManager interface for the GATT Application root ---
 * BlueZ calls GetManagedObjects() on this path to discover all GATT
 * services and characteristics registered by this application.
 */
static const gchar app_introspection_xml[] =
    "<node>"
    "  <interface name='org.freedesktop.DBus.ObjectManager'>"
    "    <method name='GetManagedObjects'>"
    "      <arg name='objects' type='a{oa{sa{sv}}}' direction='out'/>"
    "    </method>"
    "  </interface>"
    "</node>";

/* --- GattService1 interface ---
 * Exposes the service UUID, primary flag, and list of child characteristics.
 */
static const gchar service_introspection_xml[] =
    "<node>"
    "  <interface name='org.bluez.GattService1'>"
    "    <property name='UUID' type='s' access='read'/>"
    "    <property name='Primary' type='b' access='read'/>"
    "    <property name='Characteristics' type='ao' access='read'/>"
    "  </interface>"
    "</node>";

/* --- GattCharacteristic1 interface (command — write) ---
 * The WriteValue method is called by BlueZ when the phone writes to this
 * characteristic. The value is a byte array (ay), and options is a dict.
 */
static const gchar cmd_char_introspection_xml[] =
    "<node>"
    "  <interface name='org.bluez.GattCharacteristic1'>"
    "    <method name='WriteValue'>"
    "      <arg name='value' type='ay' direction='in'/>"
    "      <arg name='options' type='a{sv}' direction='in'/>"
    "    </method>"
    "    <property name='UUID' type='s' access='read'/>"
    "    <property name='Service' type='o' access='read'/>"
    "    <property name='Flags' type='as' access='read'/>"
    "  </interface>"
    "</node>";

/* --- GattCharacteristic1 interface (telemetry — read + notify) ---
 * ReadValue is called when the phone reads the value.
 * StartNotify/StopNotify manage subscription for push notifications.
 */
static const gchar tel_char_introspection_xml[] =
    "<node>"
    "  <interface name='org.bluez.GattCharacteristic1'>"
    "    <method name='ReadValue'>"
    "      <arg name='options' type='a{sv}' direction='in'/>"
    "      <arg name='value' type='ay' direction='out'/>"
    "    </method>"
    "    <method name='StartNotify'/>"
    "    <method name='StopNotify'/>"
    "    <property name='UUID' type='s' access='read'/>"
    "    <property name='Service' type='o' access='read'/>"
    "    <property name='Flags' type='as' access='read'/>"
    "    <property name='Notifying' type='b' access='read'/>"
    "  </interface>"
    "</node>";

/* --- LEAdvertisement1 interface ---
 * Defines the BLE advertisement packet content: service UUIDs, local name,
 * and advertisement type.
 */
static const gchar adv_introspection_xml[] =
    "<node>"
    "  <interface name='org.bluez.LEAdvertisement1'>"
    "    <method name='Release'/>"
    "    <property name='Type' type='s' access='read'/>"
    "    <property name='ServiceUUIDs' type='as' access='read'/>"
    "    <property name='LocalName' type='s' access='read'/>"
    "  </interface>"
    "</node>";

/* --- Agent1 interface (pairing agent — NoInputNoOutput) ---
 * BlueZ calls these methods during pairing:
 *   Release          — agent is being unregistered
 *   RequestConfirmation — confirm a numeric passkey (we auto-accept)
 *   RequestAuthorization — authorize a connection (we auto-accept)
 *   AuthorizeService — authorize a specific service (we auto-accept)
 *   Cancel           — pairing was cancelled
 *
 * For "Just Works" pairing with NoInputNoOutput capability, BlueZ
 * typically only calls RequestConfirmation (if the remote device
 * supports Secure Connections) or nothing at all (legacy pairing).
 * We implement all methods for robustness.
 */
static const gchar agent_introspection_xml[] =
    "<node>"
    "  <interface name='org.bluez.Agent1'>"
    "    <method name='Release'/>"
    "    <method name='RequestPinCode'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='pincode' type='s' direction='out'/>"
    "    </method>"
    "    <method name='RequestPasskey'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='passkey' type='u' direction='out'/>"
    "    </method>"
    "    <method name='DisplayPasskey'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='passkey' type='u' direction='in'/>"
    "      <arg name='entered' type='q' direction='in'/>"
    "    </method>"
    "    <method name='DisplayPinCode'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='pincode' type='s' direction='in'/>"
    "    </method>"
    "    <method name='RequestConfirmation'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='passkey' type='u' direction='in'/>"
    "    </method>"
    "    <method name='RequestAuthorization'>"
    "      <arg name='device' type='o' direction='in'/>"
    "    </method>"
    "    <method name='AuthorizeService'>"
    "      <arg name='device' type='o' direction='in'/>"
    "      <arg name='uuid' type='s' direction='in'/>"
    "    </method>"
    "    <method name='Cancel'/>"
    "  </interface>"
    "</node>";

/* Track whether a client has subscribed to telemetry notifications */
static gboolean telemetry_notifying = FALSE;

/* ============================================================================
 * COMMAND PARSER
 * ============================================================================
 * Decodes a UTF-8 command string received from the phone app and updates
 * the global motor state accordingly. Commands are simple ASCII strings:
 *   "FWD", "REV", "START", "STOP", "SPD:XX"
 */
static void parse_command(const char *cmd)
{
    printf("[PARMCO] Received command: \"%s\"\n", cmd);

    if (strcmp(cmd, "FWD") == 0) {
        /* Set motor direction to forward (clockwise) */
        strncpy(motor_state.direction, "FWD", sizeof(motor_state.direction));
        printf("[PARMCO] Direction → FORWARD\n");

    } else if (strcmp(cmd, "REV") == 0) {
        /* Set motor direction to reverse (counterclockwise) */
        strncpy(motor_state.direction, "REV", sizeof(motor_state.direction));
        printf("[PARMCO] Direction → REVERSE\n");

    } else if (strcmp(cmd, "START") == 0) {
        /* Enable the motor — it will spin at the current speed/direction */
        motor_state.running = 1;
        printf("[PARMCO] Motor → RUNNING\n");

    } else if (strcmp(cmd, "STOP") == 0) {
        /* Disable the motor — it will coast to a stop */
        motor_state.running = 0;
        printf("[PARMCO] Motor → STOPPED\n");

    } else if (strncmp(cmd, "SPD:", 4) == 0) {
        /* Parse the speed value following the "SPD:" prefix */
        int spd = atoi(cmd + 4);
        /* Clamp to valid range [0, 100] */
        if (spd < 0)   spd = 0;
        if (spd > 100)  spd = 100;
        motor_state.speed = spd;
        printf("[PARMCO] Speed → %d%%\n", motor_state.speed);

    /* === HUMAN EDIT START (CP3 Phase 1 F3, Jalen) === */
    } else if (strncmp(cmd, "RPM:", 4) == 0) {
        /* Target-RPM setpoint from the phone. In CP3 this was purely
         * advisory (logged but never acted on) because auto modes were
         * out of scope. In the final build MAINTAIN mode reads this
         * value directly — see update_maintain_mode(). */
        int target = atoi(cmd + 4);
        if (target < TARGET_RPM_MIN) target = TARGET_RPM_MIN;
        if (target > TARGET_RPM_MAX) target = TARGET_RPM_MAX;
        motor_state.target_rpm = target;
        printf("[PARMCO] Target RPM → %d\n", motor_state.target_rpm);
    /* === HUMAN EDIT END === */

    /* === HUMAN EDIT START (Final, Jalen) ===
     * Three mode-change commands complete the phone-side vocabulary:
     *
     *   MODE:MANUAL    → passthrough of SPD:<0-100> to PWM
     *   AUTO:MAINTAIN  → closed loop on motor's own IR, target = RPM:<n>
     *   AUTO:MATCH     → closed loop tracking GPIO23 reference source
     *
     * Each branch just stamps motor_state.mode. The controller tick
     * picks it up on the next 250ms cycle. motor_hw_apply() at the
     * end of this function re-seeds pwm_duty if we're transitioning
     * from MANUAL to an auto mode with the motor already spinning,
     * so the controller doesn't start from zero. */
    } else if (strcmp(cmd, "MODE:MANUAL") == 0) {
        motor_state.mode = MODE_MANUAL;
        /* Drop the controller-owned duty back to whatever the manual
         * speed slider says, so the transition feels instantaneous. */
        motor_state.pwm_duty = (motor_state.speed * PWM_MAX_DUTY) / 100;
        printf("[PARMCO] Mode → MANUAL\n");

    } else if (strcmp(cmd, "AUTO:MAINTAIN") == 0) {
        motor_state.mode = MODE_MAINTAIN;
        printf("[PARMCO] Mode → MAINTAIN (target=%d)\n",
               motor_state.target_rpm);

    } else if (strcmp(cmd, "AUTO:MATCH") == 0) {
        motor_state.mode = MODE_MATCH;
        printf("[PARMCO] Mode → MATCH (ref=%d)\n",
               motor_state.ref_rpm);
    /* === HUMAN EDIT END === */

    } else {
        printf("[PARMCO] Unknown command: \"%s\"\n", cmd);
    }

    /* === HUMAN EDIT START (CP3 Phase 0, Jalen) ===
     * Push the logical motor state out to the L293D pins. Without this call
     * the BLE server just updated a struct — the motor never moved.
     */
    motor_hw_apply();
    /* === HUMAN EDIT END === */
}

/* ============================================================================
 * D-BUS METHOD HANDLERS
 * ============================================================================
 * Each handler responds to a specific D-Bus method call from BlueZ.
 * GDBus dispatches calls to these functions based on the interface and
 * method name defined in the introspection XML.
 */

/* --------------------------------------------------------------------------
 * GetManagedObjects — called by BlueZ on the application root path.
 * --------------------------------------------------------------------------
 * BlueZ invokes this to discover the full GATT hierarchy. We must return
 * a dictionary mapping each object path to its interfaces and properties.
 * The response type is: a{oa{sa{sv}}}
 *   - outer dict: object path → interfaces
 *   - middle dict: interface name → properties
 *   - inner dict: property name → value variant
 */
static void handle_get_managed_objects(GDBusConnection       *conn,
                                       const gchar           *sender,
                                       const gchar           *object_path,
                                       const gchar           *interface_name,
                                       const gchar           *method_name,
                                       GVariant              *parameters,
                                       GDBusMethodInvocation *invocation,
                                       gpointer               user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)method_name; (void)parameters; (void)user_data;

    GVariantBuilder objects;   /* a{oa{sa{sv}}} */
    GVariantBuilder ifaces;    /* a{sa{sv}} */
    GVariantBuilder props;     /* a{sv} */

    g_variant_builder_init(&objects, G_VARIANT_TYPE("a{oa{sa{sv}}}"));

    /* ---- SERVICE object ---- */
    g_variant_builder_init(&ifaces, G_VARIANT_TYPE("a{sa{sv}}"));
    g_variant_builder_init(&props, G_VARIANT_TYPE("a{sv}"));

    /* UUID property: the custom PARMCO service UUID */
    g_variant_builder_add(&props, "{sv}", "UUID",
                          g_variant_new_string(PARMCO_SERVICE_UUID));
    /* Primary: this is a primary service (not included/secondary) */
    g_variant_builder_add(&props, "{sv}", "Primary",
                          g_variant_new_boolean(TRUE));
    /* Characteristics: list of object paths for child characteristics */
    const gchar *char_paths[] = { CMD_CHAR_PATH, TEL_CHAR_PATH, NULL };
    g_variant_builder_add(&props, "{sv}", "Characteristics",
                          g_variant_new_objv(char_paths, -1));

    g_variant_builder_add(&ifaces, "{sa{sv}}", "org.bluez.GattService1",
                          &props);
    g_variant_builder_add(&objects, "{oa{sa{sv}}}", SERVICE_PATH, &ifaces);

    /* ---- COMMAND CHARACTERISTIC object ---- */
    g_variant_builder_init(&ifaces, G_VARIANT_TYPE("a{sa{sv}}"));
    g_variant_builder_init(&props, G_VARIANT_TYPE("a{sv}"));

    g_variant_builder_add(&props, "{sv}", "UUID",
                          g_variant_new_string(COMMAND_CHAR_UUID));
    g_variant_builder_add(&props, "{sv}", "Service",
                          g_variant_new_object_path(SERVICE_PATH));

    /* Flags: "write" + "write-without-response" allows the phone to write
     * command bytes. "write-without-response" avoids triggering SMP pairing
     * on iOS — the ATT Write Without Response path does not require an
     * authenticated link, which prevents the pairing hang. */
    GVariantBuilder cmd_flags;
    g_variant_builder_init(&cmd_flags, G_VARIANT_TYPE("as"));
    g_variant_builder_add(&cmd_flags, "s", "write");
    g_variant_builder_add(&cmd_flags, "s", "write-without-response");
    g_variant_builder_add(&props, "{sv}", "Flags",
                          g_variant_builder_end(&cmd_flags));

    g_variant_builder_add(&ifaces, "{sa{sv}}",
                          "org.bluez.GattCharacteristic1", &props);
    g_variant_builder_add(&objects, "{oa{sa{sv}}}", CMD_CHAR_PATH, &ifaces);

    /* ---- TELEMETRY CHARACTERISTIC object ---- */
    g_variant_builder_init(&ifaces, G_VARIANT_TYPE("a{sa{sv}}"));
    g_variant_builder_init(&props, G_VARIANT_TYPE("a{sv}"));

    g_variant_builder_add(&props, "{sv}", "UUID",
                          g_variant_new_string(TELEMETRY_CHAR_UUID));
    g_variant_builder_add(&props, "{sv}", "Service",
                          g_variant_new_object_path(SERVICE_PATH));

    /* Flags: "read" + "notify" — phone can poll or subscribe to RPM */
    GVariantBuilder tel_flags;
    g_variant_builder_init(&tel_flags, G_VARIANT_TYPE("as"));
    g_variant_builder_add(&tel_flags, "s", "read");
    g_variant_builder_add(&tel_flags, "s", "notify");
    g_variant_builder_add(&props, "{sv}", "Flags",
                          g_variant_builder_end(&tel_flags));

    g_variant_builder_add(&ifaces, "{sa{sv}}",
                          "org.bluez.GattCharacteristic1", &props);
    g_variant_builder_add(&objects, "{oa{sa{sv}}}", TEL_CHAR_PATH, &ifaces);

    /* Return the complete object hierarchy to BlueZ */
    g_dbus_method_invocation_return_value(
        invocation,
        g_variant_new("(a{oa{sa{sv}}})", &objects)
    );
}

/* --------------------------------------------------------------------------
 * Service property getter — returns properties for GattService1
 * -------------------------------------------------------------------------- */
static GVariant *handle_service_get_property(GDBusConnection  *conn,
                                             const gchar      *sender,
                                             const gchar      *object_path,
                                             const gchar      *interface_name,
                                             const gchar      *property_name,
                                             GError          **error,
                                             gpointer          user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)user_data;

    if (g_strcmp0(property_name, "UUID") == 0)
        return g_variant_new_string(PARMCO_SERVICE_UUID);

    if (g_strcmp0(property_name, "Primary") == 0)
        return g_variant_new_boolean(TRUE);

    if (g_strcmp0(property_name, "Characteristics") == 0) {
        const gchar *paths[] = { CMD_CHAR_PATH, TEL_CHAR_PATH, NULL };
        return g_variant_new_objv(paths, -1);
    }

    g_set_error(error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS,
                "Unknown property: %s", property_name);
    return NULL;
}

/* --------------------------------------------------------------------------
 * Command characteristic — WriteValue handler
 * --------------------------------------------------------------------------
 * Called by BlueZ when the phone writes bytes to the command characteristic.
 * The first parameter is a byte array (ay) containing the UTF-8 command.
 * The second parameter is an options dict (a{sv}) — unused here.
 */
static void handle_cmd_method_call(GDBusConnection       *conn,
                                   const gchar           *sender,
                                   const gchar           *object_path,
                                   const gchar           *interface_name,
                                   const gchar           *method_name,
                                   GVariant              *parameters,
                                   GDBusMethodInvocation *invocation,
                                   gpointer               user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)user_data;

    if (g_strcmp0(method_name, "WriteValue") == 0) {
        /* Extract the byte array from the D-Bus message.
         * parameters type is (aya{sv}) — byte array + options dict. */
        GVariant *value_variant = NULL;
        GVariant *options_variant = NULL;
        g_variant_get(parameters, "(@ay@a{sv})", &value_variant, &options_variant);

        /* Get the raw byte data and its length */
        gsize len = 0;
        const guint8 *bytes = g_variant_get_fixed_array(value_variant, &len,
                                                         sizeof(guint8));

        /* Convert byte array to a null-terminated C string.
         * Allocate len+1 bytes to ensure null termination. */
        char *cmd = g_malloc0(len + 1);
        memcpy(cmd, bytes, len);
        cmd[len] = '\0';

        /* Parse and execute the command */
        parse_command(cmd);

        g_free(cmd);
        g_variant_unref(value_variant);
        g_variant_unref(options_variant);

        /* Return success (no output parameters for WriteValue) */
        g_dbus_method_invocation_return_value(invocation, NULL);
    }
}

/* --------------------------------------------------------------------------
 * Command characteristic property getter
 * -------------------------------------------------------------------------- */
static GVariant *handle_cmd_get_property(GDBusConnection  *conn,
                                         const gchar      *sender,
                                         const gchar      *object_path,
                                         const gchar      *interface_name,
                                         const gchar      *property_name,
                                         GError          **error,
                                         gpointer          user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)user_data;

    if (g_strcmp0(property_name, "UUID") == 0)
        return g_variant_new_string(COMMAND_CHAR_UUID);

    if (g_strcmp0(property_name, "Service") == 0)
        return g_variant_new_object_path(SERVICE_PATH);

    if (g_strcmp0(property_name, "Flags") == 0) {
        GVariantBuilder flags;
        g_variant_builder_init(&flags, G_VARIANT_TYPE("as"));
        g_variant_builder_add(&flags, "s", "write");
        g_variant_builder_add(&flags, "s", "write-without-response");
        return g_variant_builder_end(&flags);
    }

    g_set_error(error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS,
                "Unknown property: %s", property_name);
    return NULL;
}

/* --------------------------------------------------------------------------
 * Telemetry characteristic — ReadValue / StartNotify / StopNotify handlers
 * -------------------------------------------------------------------------- */
static void handle_tel_method_call(GDBusConnection       *conn,
                                   const gchar           *sender,
                                   const gchar           *object_path,
                                   const gchar           *interface_name,
                                   const gchar           *method_name,
                                   GVariant              *parameters,
                                   GDBusMethodInvocation *invocation,
                                   gpointer               user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)parameters; (void)user_data;

    if (g_strcmp0(method_name, "ReadValue") == 0) {
        /* Convert the current RPM integer to a UTF-8 string, then to bytes.
         * The phone app will decode these bytes back into a string. */
        char rpm_str[16];
        snprintf(rpm_str, sizeof(rpm_str), "%d", motor_state.rpm);

        /* Build the byte array variant (ay) for the return value */
        GVariantBuilder builder;
        g_variant_builder_init(&builder, G_VARIANT_TYPE("ay"));
        for (size_t i = 0; i < strlen(rpm_str); i++) {
            g_variant_builder_add(&builder, "y", (guint8)rpm_str[i]);
        }

        g_dbus_method_invocation_return_value(
            invocation,
            g_variant_new("(ay)", &builder)
        );

    } else if (g_strcmp0(method_name, "StartNotify") == 0) {
        /* The phone has subscribed to RPM notifications.
         * BlueZ will now forward PropertiesChanged signals to the client. */
        telemetry_notifying = TRUE;
        printf("[PARMCO] Telemetry notifications → ENABLED\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "StopNotify") == 0) {
        /* The phone has unsubscribed from RPM notifications. */
        telemetry_notifying = FALSE;
        printf("[PARMCO] Telemetry notifications → DISABLED\n");
        g_dbus_method_invocation_return_value(invocation, NULL);
    }
}

/* --------------------------------------------------------------------------
 * Telemetry characteristic property getter
 * -------------------------------------------------------------------------- */
static GVariant *handle_tel_get_property(GDBusConnection  *conn,
                                         const gchar      *sender,
                                         const gchar      *object_path,
                                         const gchar      *interface_name,
                                         const gchar      *property_name,
                                         GError          **error,
                                         gpointer          user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)user_data;

    if (g_strcmp0(property_name, "UUID") == 0)
        return g_variant_new_string(TELEMETRY_CHAR_UUID);

    if (g_strcmp0(property_name, "Service") == 0)
        return g_variant_new_object_path(SERVICE_PATH);

    if (g_strcmp0(property_name, "Flags") == 0) {
        GVariantBuilder flags;
        g_variant_builder_init(&flags, G_VARIANT_TYPE("as"));
        g_variant_builder_add(&flags, "s", "read");
        g_variant_builder_add(&flags, "s", "notify");
        return g_variant_builder_end(&flags);
    }

    if (g_strcmp0(property_name, "Notifying") == 0)
        return g_variant_new_boolean(telemetry_notifying);

    g_set_error(error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS,
                "Unknown property: %s", property_name);
    return NULL;
}

/* --------------------------------------------------------------------------
 * Advertisement — Release handler (called by BlueZ when adv is unregistered)
 * -------------------------------------------------------------------------- */
static void handle_adv_method_call(GDBusConnection       *conn,
                                   const gchar           *sender,
                                   const gchar           *object_path,
                                   const gchar           *interface_name,
                                   const gchar           *method_name,
                                   GVariant              *parameters,
                                   GDBusMethodInvocation *invocation,
                                   gpointer               user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)parameters; (void)user_data;

    if (g_strcmp0(method_name, "Release") == 0) {
        printf("[PARMCO] Advertisement released by BlueZ.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);
    }
}

/* --------------------------------------------------------------------------
 * Advertisement property getter
 * -------------------------------------------------------------------------- */
static GVariant *handle_adv_get_property(GDBusConnection  *conn,
                                         const gchar      *sender,
                                         const gchar      *object_path,
                                         const gchar      *interface_name,
                                         const gchar      *property_name,
                                         GError          **error,
                                         gpointer          user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)user_data;

    /* Type: "peripheral" tells BlueZ this is a connectable advertisement */
    if (g_strcmp0(property_name, "Type") == 0)
        return g_variant_new_string("peripheral");

    /* ServiceUUIDs: the phone filters its BLE scan by this UUID */
    if (g_strcmp0(property_name, "ServiceUUIDs") == 0) {
        GVariantBuilder uuids;
        g_variant_builder_init(&uuids, G_VARIANT_TYPE("as"));
        g_variant_builder_add(&uuids, "s", PARMCO_SERVICE_UUID);
        return g_variant_builder_end(&uuids);
    }

    /* LocalName: appears in the phone's Bluetooth device list */
    if (g_strcmp0(property_name, "LocalName") == 0)
        return g_variant_new_string("PARMCO-RP4");

    g_set_error(error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS,
                "Unknown property: %s", property_name);
    return NULL;
}

/* --------------------------------------------------------------------------
 * Pairing Agent — NoInputNoOutput auto-accept handler
 * --------------------------------------------------------------------------
 * This handler responds to ALL BlueZ Agent1 method calls. The agent's
 * role is to handle the human side of Bluetooth pairing — displaying
 * passkeys, confirming numeric comparisons, entering PINs, etc.
 *
 * With the "NoInputNoOutput" capability, BlueZ tells the remote device
 * (the iPhone) that this device cannot display or input anything. The
 * result is "Just Works" pairing:
 *   - No PIN prompt on either device
 *   - No numeric comparison confirmation
 *   - The link is encrypted but not authenticated (no MITM protection)
 *
 * For PARMCO, this is the correct approach because:
 *   1. We're sending motor commands, not sensitive data
 *   2. The system operates in a controlled lab environment
 *   3. User-interactive pairing is impractical on a headless RP4
 *
 * WHAT WAS HAPPENING WITHOUT THIS AGENT:
 *   When iOS connected and BlueZ initiated SMP pairing (triggered by
 *   the "write" flag on the command characteristic or by iOS probing
 *   standard GATT services), BlueZ dispatched a pairing request to
 *   the registered agent. With NO agent registered, the request sat
 *   in a queue with no handler, producing:
 *     - RP4 side: "Waiting for response from Bluetooth device"
 *     - iPhone side: pairing dialog that eventually times out
 *   Registering this agent ensures every pairing request gets an
 *   immediate "yes" response.
 */
static void handle_agent_method_call(GDBusConnection       *conn,
                                     const gchar           *sender,
                                     const gchar           *object_path,
                                     const gchar           *interface_name,
                                     const gchar           *method_name,
                                     GVariant              *parameters,
                                     GDBusMethodInvocation *invocation,
                                     gpointer               user_data)
{
    (void)conn; (void)sender; (void)object_path;
    (void)interface_name; (void)parameters; (void)user_data;

    if (g_strcmp0(method_name, "RequestConfirmation") == 0) {
        /* Numeric comparison: BlueZ shows a 6-digit number and asks us
         * to confirm it matches what the remote device shows. With
         * NoInputNoOutput, we auto-accept — "Just Works" pairing. */
        printf("[PARMCO] Agent: RequestConfirmation — auto-accepting.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "RequestAuthorization") == 0) {
        /* BlueZ asks if we authorize this device to connect. Auto-accept. */
        printf("[PARMCO] Agent: RequestAuthorization — auto-accepting.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "AuthorizeService") == 0) {
        /* BlueZ asks if we authorize access to a specific service UUID.
         * Auto-accept — all services on this device are public. */
        printf("[PARMCO] Agent: AuthorizeService — auto-accepting.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "RequestPinCode") == 0) {
        /* Legacy PIN code pairing (Bluetooth 2.0 style). Unlikely for
         * BLE, but handle it by returning a default PIN. */
        printf("[PARMCO] Agent: RequestPinCode — returning '0000'.\n");
        g_dbus_method_invocation_return_value(
            invocation, g_variant_new("(s)", "0000"));

    } else if (g_strcmp0(method_name, "RequestPasskey") == 0) {
        /* Passkey entry: return a numeric passkey. Unlikely for
         * NoInputNoOutput capability but handle for completeness. */
        printf("[PARMCO] Agent: RequestPasskey — returning 0.\n");
        g_dbus_method_invocation_return_value(
            invocation, g_variant_new("(u)", (guint32)0));

    } else if (g_strcmp0(method_name, "DisplayPasskey") == 0) {
        /* BlueZ wants us to display a passkey to the user. On a headless
         * device, we just log it. */
        const gchar *device = NULL;
        guint32 passkey = 0;
        guint16 entered = 0;
        g_variant_get(parameters, "(&ouq)", &device, &passkey, &entered);
        printf("[PARMCO] Agent: DisplayPasskey — device=%s passkey=%06u entered=%u\n",
               device, passkey, entered);
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "DisplayPinCode") == 0) {
        /* Display a PIN code. Log it and return. */
        const gchar *device = NULL;
        const gchar *pincode = NULL;
        g_variant_get(parameters, "(&o&s)", &device, &pincode);
        printf("[PARMCO] Agent: DisplayPinCode — device=%s pin=%s\n",
               device, pincode);
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "Release") == 0) {
        /* BlueZ is unregistering this agent. */
        printf("[PARMCO] Agent: Released by BlueZ.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else if (g_strcmp0(method_name, "Cancel") == 0) {
        /* A pairing operation was cancelled. */
        printf("[PARMCO] Agent: Pairing cancelled.\n");
        g_dbus_method_invocation_return_value(invocation, NULL);

    } else {
        /* Unknown agent method — should never happen */
        printf("[PARMCO] Agent: Unknown method '%s'\n", method_name);
        g_dbus_method_invocation_return_value(invocation, NULL);
    }
}

/* ============================================================================
 * TELEMETRY TIMER CALLBACK
 * ============================================================================
 * Called every TELEMETRY_INTERVAL_MS by the GLib main loop. If a client
 * has subscribed to notifications (telemetry_notifying == TRUE), this emits
 * a PropertiesChanged signal on the telemetry characteristic with the
 * updated RPM value. BlueZ intercepts this signal and pushes the data
 * to the connected phone over the air.
 */
static gboolean telemetry_timer_callback(gpointer user_data)
{
    (void)user_data;

    /* === HUMAN EDIT START (CP3 Phase 1 F2, Jalen) ===
     * Dual-rate cadence: fire every tick (5 Hz) while the motor is running,
     * and skip 4 of every 5 ticks while idle to drop to 1 Hz. */
    static int idle_skip = 0;
    if (!motor_state.running) {
        if (++idle_skip < 5) return G_SOURCE_CONTINUE;
        idle_skip = 0;
    } else {
        idle_skip = 0;
    }
    /* === HUMAN EDIT END === */

    /* === HUMAN EDIT START (Final, Jalen) ===
     * RPM sampling migrated out of here and into controller_timer_callback.
     * This function now just publishes whatever the controller tick last
     * measured — motor_state.rpm and motor_state.ref_rpm. Two reasons:
     *   1. The controller needs the fresh sample first; otherwise MAINTAIN
     *      and MATCH would always be correcting against last cycle's data.
     *   2. Both callbacks hitting motor_hw_sample_rpm() would compete for
     *      the sliding-window static state and desync the window.
     *
     * Idle gating still zeroes the published values so the phone shows 0
     * when the motor is stopped instead of a stale reading. */
    if (!motor_state.running) {
        motor_state.rpm     = 0;
        motor_state.ref_rpm = 0;
    }
    /* === HUMAN EDIT END === */

    /* Only emit notifications if a client is subscribed */
    if (!telemetry_notifying || dbus_conn == NULL)
        return G_SOURCE_CONTINUE;

    /* === HUMAN EDIT START (Final, Jalen) ===
     * Extended payload: "RPM:<actual>,REF:<ref>,M:<mode>"
     *
     * Rationale: three fields the phone needs every tick —
     *   RPM: actual motor RPM (displayed in the big reading)
     *   REF: reference RPM from GPIO23 (displayed when in MATCH mode)
     *   M:   which controller is active (so the UI can echo back what
     *        the phone requested and confirm the RP4 is in sync)
     *
     * ASCII + comma-separated instead of JSON to avoid pulling a JSON
     * library into the Swift BLE parser. Each field keeps its key
     * prefix so fields can appear in any order (and the CP3 parser's
     * "RPM:<int>" prefix-strip still works on the first field).
     *
     * 48 bytes is plenty — the ATT MTU on the iPhone is 185 bytes
     * after negotiation, and a maximal payload here is under 40. */
    const char *mode_str =
        (motor_state.mode == MODE_MAINTAIN) ? "maintain" :
        (motor_state.mode == MODE_MATCH)    ? "match"    : "manual";

    char rpm_str[64];
    snprintf(rpm_str, sizeof(rpm_str),
             "RPM:%d,REF:%d,M:%s",
             motor_state.rpm,
             motor_state.ref_rpm,
             mode_str);
    /* === HUMAN EDIT END === */

    GVariantBuilder value_builder;
    g_variant_builder_init(&value_builder, G_VARIANT_TYPE("ay"));
    for (size_t i = 0; i < strlen(rpm_str); i++) {
        g_variant_builder_add(&value_builder, "y", (guint8)rpm_str[i]);
    }

    /* Build the PropertiesChanged signal arguments:
     *   interface_name: "org.bluez.GattCharacteristic1"
     *   changed_properties: { "Value": <byte array> }
     *   invalidated_properties: [] (empty)
     */
    GVariantBuilder changed;
    g_variant_builder_init(&changed, G_VARIANT_TYPE("a{sv}"));
    g_variant_builder_add(&changed, "{sv}", "Value",
                          g_variant_builder_end(&value_builder));

    GVariantBuilder invalidated;
    g_variant_builder_init(&invalidated, G_VARIANT_TYPE("as"));

    /* Emit the signal on the telemetry characteristic's object path.
     * BlueZ monitors for PropertiesChanged on GattCharacteristic1 objects
     * and forwards the Value change to any subscribed BLE central. */
    GError *err = NULL;
    g_dbus_connection_emit_signal(
        dbus_conn,
        NULL,                                       /* broadcast to all */
        TEL_CHAR_PATH,                              /* object path */
        "org.freedesktop.DBus.Properties",          /* interface */
        "PropertiesChanged",                        /* signal name */
        g_variant_new("(sa{sv}as)",
                      "org.bluez.GattCharacteristic1",
                      &changed,
                      &invalidated),
        &err
    );

    if (err) {
        fprintf(stderr, "[PARMCO] Error emitting telemetry: %s\n", err->message);
        g_error_free(err);
    }

    return G_SOURCE_CONTINUE;  /* Keep the timer running */
}

/* ============================================================================
 * CONTROLLER TIMER CALLBACK                         === HUMAN EDIT (Final) ===
 * ============================================================================
 * Fires every CONTROL_PERIOD_MS regardless of whether a phone is connected.
 * Two jobs:
 *
 *   1. Sample both IR channels into motor_state.rpm and motor_state.ref_rpm
 *      so the telemetry tick (which runs at a separate cadence) has fresh
 *      numbers to publish.
 *
 *   2. If the motor is running AND we're in an auto mode, nudge pwm_duty
 *      by the mode's controller. MANUAL mode bypasses this — PWM in MANUAL
 *      is written synchronously by motor_hw_apply() when SPD: arrives.
 *
 * Running this as a separate GLib source (rather than folding it into the
 * telemetry callback) gives us independent tuning knobs for publish rate
 * and control rate, and keeps the telemetry code from getting tangled up
 * with controller math.
 *
 * The auto modes deliberately keep running through the controller even
 * when motor_state.running == 0 — they just skip the PWM update. This
 * keeps measurement history current so resuming from STOP doesn't start
 * with a stale window.
 */
static gboolean controller_timer_callback(gpointer user_data)
{
    (void)user_data;

    /* Always sample the sensors. Zero out the reading if the motor is
     * stopped rather than trusting the tach (which will show residual
     * coast-down pulses for a second or two after STOP). */
    if (motor_state.running) {
        motor_state.rpm     = motor_hw_sample_rpm();
        motor_state.ref_rpm = motor_hw_sample_ref_rpm();
    } else {
        motor_state.rpm     = 0;
        motor_state.ref_rpm = motor_hw_sample_ref_rpm();
        /* Note we still read the reference even with motor stopped.
         * A bench function generator running continuously is often how
         * we arm MATCH mode BEFORE pressing START on the phone. */
    }

    /* Only the auto modes want controller action. MANUAL's PWM was
     * already written by motor_hw_apply() when SPD: arrived. */
    if (!motor_state.running) return G_SOURCE_CONTINUE;

    switch (motor_state.mode) {
        case MODE_MAINTAIN: update_maintain_mode(); break;
        case MODE_MATCH:    update_match_mode();    break;
        case MODE_MANUAL:
        default:            /* nothing — MANUAL is synchronous */ break;
    }

    return G_SOURCE_CONTINUE;
}
/* === HUMAN EDIT END === */

/* ============================================================================
 * D-BUS VIRTUAL TABLE DEFINITIONS
 * ============================================================================
 * GDBus uses virtual tables (vtables) to dispatch method calls and property
 * reads to the appropriate handler functions. Each registered object path
 * gets its own vtable.
 */

/* Application root — only responds to GetManagedObjects */
static const GDBusInterfaceVTable app_vtable = {
    .method_call  = handle_get_managed_objects,
    .get_property = NULL,
    .set_property = NULL
};

/* Service object — only has properties, no callable methods */
static const GDBusInterfaceVTable service_vtable = {
    .method_call  = NULL,
    .get_property = handle_service_get_property,
    .set_property = NULL
};

/* Command characteristic — WriteValue method + properties */
static const GDBusInterfaceVTable cmd_char_vtable = {
    .method_call  = handle_cmd_method_call,
    .get_property = handle_cmd_get_property,
    .set_property = NULL
};

/* Telemetry characteristic — ReadValue/StartNotify/StopNotify + properties */
static const GDBusInterfaceVTable tel_char_vtable = {
    .method_call  = handle_tel_method_call,
    .get_property = handle_tel_get_property,
    .set_property = NULL
};

/* Advertisement — Release method + properties */
static const GDBusInterfaceVTable adv_vtable = {
    .method_call  = handle_adv_method_call,
    .get_property = handle_adv_get_property,
    .set_property = NULL
};

/* Pairing agent — handles all Agent1 method calls (auto-accept) */
static const GDBusInterfaceVTable agent_vtable = {
    .method_call  = handle_agent_method_call,
    .get_property = NULL,
    .set_property = NULL
};

/* ============================================================================
 * REGISTRATION HELPERS
 * ============================================================================
 * These functions register each D-Bus object with the system bus using the
 * introspection XML and vtable defined above.
 */

/**
 * register_object — register a single D-Bus object at the given path.
 *
 * @param conn         The D-Bus connection
 * @param path         Object path (e.g., "/com/parmco/service0")
 * @param xml          Introspection XML defining the interface
 * @param vtable       Method call and property handler dispatch table
 * @param description  Human-readable name for error messages
 * @return             Registration ID (nonzero on success, 0 on failure)
 */
static guint register_object(GDBusConnection             *conn,
                              const gchar                 *path,
                              const gchar                 *xml,
                              const GDBusInterfaceVTable  *vtable,
                              const char                  *description)
{
    GError *err = NULL;

    /* Parse the introspection XML into a GDBusNodeInfo structure */
    GDBusNodeInfo *node_info = g_dbus_node_info_new_for_xml(xml, &err);
    if (err) {
        fprintf(stderr, "[PARMCO] Failed to parse %s XML: %s\n",
                description, err->message);
        g_error_free(err);
        return 0;
    }

    /* Register the object on the bus. BlueZ will discover it via
     * GetManagedObjects or by probing the object path directly. */
    guint reg_id = g_dbus_connection_register_object(
        conn,
        path,
        node_info->interfaces[0],  /* First (and only) interface in the XML */
        vtable,
        NULL,   /* user_data — not needed; we use globals */
        NULL,   /* GDestroyNotify — no cleanup needed */
        &err
    );

    if (err) {
        fprintf(stderr, "[PARMCO] Failed to register %s: %s\n",
                description, err->message);
        g_error_free(err);
        g_dbus_node_info_unref(node_info);
        return 0;
    }

    printf("[PARMCO] Registered %s at %s\n", description, path);

    /* Note: node_info is intentionally NOT unreffed here.
     * GDBus holds a reference to the interface info internally and requires
     * it to remain valid for the lifetime of the registration. Freeing it
     * here would cause use-after-free crashes on the first method call.
     * It will be freed when the program exits. */

    return reg_id;
}

/* ============================================================================
 * BLUEZ REGISTRATION CALLBACKS
 * ============================================================================
 * Called when BlueZ responds to our RegisterApplication / RegisterAdvertisement
 * D-Bus method calls. On success, the GATT server or advertisement is live.
 */

static void on_app_registered(GObject *source, GAsyncResult *res, gpointer data)
{
    (void)data;
    GError *err = NULL;
    GVariant *result = g_dbus_connection_call_finish(
        G_DBUS_CONNECTION(source), res, &err);

    if (err) {
        fprintf(stderr, "[PARMCO] Failed to register GATT application: %s\n",
                err->message);
        g_error_free(err);
        return;
    }

    printf("[PARMCO] GATT application registered with BlueZ.\n");
    if (result) g_variant_unref(result);
}

static void on_adv_registered(GObject *source, GAsyncResult *res, gpointer data)
{
    (void)data;
    GError *err = NULL;
    GVariant *result = g_dbus_connection_call_finish(
        G_DBUS_CONNECTION(source), res, &err);

    if (err) {
        fprintf(stderr, "[PARMCO] Failed to register advertisement: %s\n",
                err->message);
        g_error_free(err);
        return;
    }

    printf("[PARMCO] BLE advertisement registered. Discoverable as \"PARMCO-RP4\".\n");
    if (result) g_variant_unref(result);
}

/* ============================================================================
 * SIGNAL HANDLER — Clean shutdown
 * ============================================================================
 * Catches SIGINT (Ctrl+C) and SIGTERM to gracefully stop the main loop,
 * which triggers cleanup in main(). Without this, the advertisement and
 * GATT service would remain registered in BlueZ until reboot.
 */
static void signal_handler(int signum)
{
    printf("\n[PARMCO] Caught signal %d, shutting down...\n", signum);
    if (main_loop && g_main_loop_is_running(main_loop)) {
        g_main_loop_quit(main_loop);
    }
}

/* ============================================================================
 * MAIN
 * ============================================================================ */
int main(int argc, char *argv[])
{
    (void)argc; (void)argv;

    GError *err = NULL;

    printf("============================================================\n");
    printf("  PARMCO BLE Server — ECSE 4235\n");
    printf("  University of Georgia\n");
    printf("  Justin Moreno & Jalen Edusei\n");
    printf("============================================================\n\n");

    /* --- Install signal handlers for clean shutdown --- */
    signal(SIGINT,  signal_handler);
    signal(SIGTERM, signal_handler);

    /* === HUMAN EDIT START (CP3 Phase 0, Jalen) ===
     * Bring up the motor hardware before BlueZ so the first command that
     * arrives has pins to drive. If this fails we still run the BLE side —
     * the grader at least sees advertising and logs, and we print a clear
     * error so the bench test isn't mysterious. */
    if (motor_hw_init() < 0) {
        fprintf(stderr, "[PARMCO] WARNING — motor HW init failed; "
                        "BLE will run in log-only mode.\n");
    }
    /* === HUMAN EDIT END === */

    /* --- Connect to the system D-Bus ---
     * All BlueZ communication happens on the system bus, not the session bus.
     * The program must either run as root or have appropriate D-Bus policy
     * permissions (see parmco-dbus.conf). */
    dbus_conn = g_bus_get_sync(G_BUS_TYPE_SYSTEM, NULL, &err);
    if (err) {
        fprintf(stderr, "[PARMCO] Cannot connect to system D-Bus: %s\n",
                err->message);
        g_error_free(err);
        return EXIT_FAILURE;
    }
    printf("[PARMCO] Connected to system D-Bus.\n");

    /* =================================================================
     * PAIRING AGENT REGISTRATION — must happen BEFORE GATT registration
     * =================================================================
     * The agent must be registered and set as default BEFORE we register
     * the GATT application and start advertising. If a phone connects
     * before the agent is ready, BlueZ has no handler for the pairing
     * request and will hang with "Waiting for response."
     *
     * Registration sequence:
     *   1. Register the agent D-Bus object at AGENT_PATH
     *   2. Call AgentManager1.RegisterAgent() to tell BlueZ about it
     *   3. Call AgentManager1.RequestDefaultAgent() to make it the
     *      system-wide default for all pairing requests
     */

    /* Step 1: Register the agent D-Bus object */
    agent_reg_id = register_object(dbus_conn, AGENT_PATH,
                                   agent_introspection_xml, &agent_vtable,
                                   "Pairing Agent (NoInputNoOutput)");
    if (!agent_reg_id) {
        fprintf(stderr, "[PARMCO] Failed to register pairing agent object.\n");
        return EXIT_FAILURE;
    }

    /* Step 2: Register the agent with BlueZ's AgentManager1.
     * Arguments: (object_path, capability_string)
     * The capability "NoInputNoOutput" tells BlueZ to use Just Works pairing. */
    printf("[PARMCO] Registering pairing agent with BlueZ...\n");
    g_dbus_connection_call_sync(
        dbus_conn,
        BLUEZ_BUS_NAME,
        "/org/bluez",              /* AgentManager1 lives on /org/bluez */
        AGENT_MANAGER_IFACE,
        "RegisterAgent",
        g_variant_new("(os)", AGENT_PATH, AGENT_CAPABILITY),
        NULL,
        G_DBUS_CALL_FLAGS_NONE,
        -1, NULL, &err
    );
    if (err) {
        fprintf(stderr, "[PARMCO] Failed to register agent: %s\n", err->message);
        fprintf(stderr, "[PARMCO] Pairing may fail — continuing anyway.\n");
        g_error_free(err);
        err = NULL;
    } else {
        printf("[PARMCO] Pairing agent registered (capability: %s).\n",
               AGENT_CAPABILITY);
    }

    /* Step 3: Set this agent as the default agent for ALL pairing requests.
     * Without this, BlueZ might use a different agent (e.g., from
     * bluetoothctl or a desktop Bluetooth manager) or no agent at all. */
    g_dbus_connection_call_sync(
        dbus_conn,
        BLUEZ_BUS_NAME,
        "/org/bluez",
        AGENT_MANAGER_IFACE,
        "RequestDefaultAgent",
        g_variant_new("(o)", AGENT_PATH),
        NULL,
        G_DBUS_CALL_FLAGS_NONE,
        -1, NULL, &err
    );
    if (err) {
        fprintf(stderr, "[PARMCO] Failed to set default agent: %s\n", err->message);
        g_error_free(err);
        err = NULL;
    } else {
        printf("[PARMCO] Pairing agent set as default.\n");
    }

    /* --- Register all GATT objects on the bus --- */
    app_reg_id = register_object(dbus_conn, APP_PATH,
                                 app_introspection_xml, &app_vtable,
                                 "Application (ObjectManager)");

    svc_reg_id = register_object(dbus_conn, SERVICE_PATH,
                                 service_introspection_xml, &service_vtable,
                                 "GATT Service");

    cmd_reg_id = register_object(dbus_conn, CMD_CHAR_PATH,
                                 cmd_char_introspection_xml, &cmd_char_vtable,
                                 "Command Characteristic");

    tel_reg_id = register_object(dbus_conn, TEL_CHAR_PATH,
                                 tel_char_introspection_xml, &tel_char_vtable,
                                 "Telemetry Characteristic");

    adv_reg_id = register_object(dbus_conn, ADV_PATH,
                                 adv_introspection_xml, &adv_vtable,
                                 "LE Advertisement");

    if (!app_reg_id || !svc_reg_id || !cmd_reg_id || !tel_reg_id || !adv_reg_id) {
        fprintf(stderr, "[PARMCO] One or more objects failed to register. Exiting.\n");
        return EXIT_FAILURE;
    }

    /* --- Register the GATT application with BlueZ ---
     * This tells BlueZ's GattManager1 to inspect our ObjectManager at APP_PATH
     * and incorporate our service/characteristics into its GATT database. */
    printf("[PARMCO] Registering GATT application with BlueZ...\n");
    g_dbus_connection_call(
        dbus_conn,
        BLUEZ_BUS_NAME,                         /* destination: BlueZ daemon */
        ADAPTER_PATH,                           /* object: the BT adapter */
        GATT_MANAGER_IFACE,                     /* interface */
        "RegisterApplication",                  /* method */
        g_variant_new("(oa{sv})",               /* arguments: (object_path, options) */
                      APP_PATH,
                      NULL),                    /* no options */
        NULL,                                   /* no expected return type */
        G_DBUS_CALL_FLAGS_NONE,
        -1,                                     /* default timeout */
        NULL,                                   /* no cancellable */
        on_app_registered,                      /* async callback */
        NULL                                    /* callback user_data */
    );

    /* --- Register the BLE advertisement with BlueZ ---
     * This tells BlueZ's LEAdvertisingManager1 to broadcast our advertisement
     * packets containing the PARMCO service UUID and local name. */
    printf("[PARMCO] Registering BLE advertisement...\n");
    g_dbus_connection_call(
        dbus_conn,
        BLUEZ_BUS_NAME,
        ADAPTER_PATH,
        LE_ADV_MANAGER_IFACE,
        "RegisterAdvertisement",
        g_variant_new("(oa{sv})",
                      ADV_PATH,
                      NULL),
        NULL,
        G_DBUS_CALL_FLAGS_NONE,
        -1,
        NULL,
        on_adv_registered,
        NULL
    );

    /* --- Start periodic telemetry updates ---
     * Every 500ms, the timer callback updates the mock RPM value and, if a
     * client is subscribed, emits a PropertiesChanged signal to push the
     * new value over BLE. */
    telemetry_timer_id = g_timeout_add(TELEMETRY_INTERVAL_MS,
                                        telemetry_timer_callback, NULL);

    /* === HUMAN EDIT START (Final, Jalen) ===
     * Controller timer. Runs at CONTROL_PERIOD_MS (250 ms) and handles
     * sensor sampling + the MAINTAIN/MATCH proportional controllers.
     * Independent of the telemetry timer so the two cadences can be
     * tuned separately — controller is fast enough to feel responsive,
     * telemetry is fast enough to feel live, neither dominates the BLE
     * notification queue. */
    controller_timer_id = g_timeout_add(CONTROL_PERIOD_MS,
                                        controller_timer_callback, NULL);
    /* === HUMAN EDIT END === */

    /* --- Enter the GLib main event loop ---
     * This loop processes all D-Bus method calls, signals, and timer events.
     * It runs until g_main_loop_quit() is called (by the signal handler). */
    printf("\n[PARMCO] PARMCO BLE Server started. Advertising...\n");
    printf("[PARMCO] Waiting for phone connection. Press Ctrl+C to stop.\n\n");

    printf("[PARMCO] Motor state: direction=%s speed=%d%% running=%s rpm=%d\n\n",
           motor_state.direction,
           motor_state.speed,
           motor_state.running ? "YES" : "NO",
           motor_state.rpm);

    main_loop = g_main_loop_new(NULL, FALSE);
    g_main_loop_run(main_loop);

    /* =====================================================================
     * CLEANUP — reached after signal handler calls g_main_loop_quit()
     * ===================================================================== */

    printf("[PARMCO] Cleaning up...\n");

    /* === HUMAN EDIT START (CP3 Phase 0, Jalen) ===
     * Kill motor power FIRST so a hung BlueZ unregister can't leave the
     * L293D sinking current into a stalled motor. */
    motor_hw_shutdown();
    /* === HUMAN EDIT END === */

    /* Remove the telemetry timer */
    if (telemetry_timer_id > 0) {
        g_source_remove(telemetry_timer_id);
        telemetry_timer_id = 0;
    }

    /* === HUMAN EDIT START (Final, Jalen) ===
     * Remove the controller timer. Ordering matters — timers before
     * D-Bus unregister so no callback fires into a torn-down connection. */
    if (controller_timer_id > 0) {
        g_source_remove(controller_timer_id);
        controller_timer_id = 0;
    }
    /* === HUMAN EDIT END === */

    /* Unregister the advertisement from BlueZ */
    if (dbus_conn) {
        g_dbus_connection_call_sync(
            dbus_conn,
            BLUEZ_BUS_NAME,
            ADAPTER_PATH,
            LE_ADV_MANAGER_IFACE,
            "UnregisterAdvertisement",
            g_variant_new("(o)", ADV_PATH),
            NULL,
            G_DBUS_CALL_FLAGS_NONE,
            -1, NULL, NULL
        );
        printf("[PARMCO] Advertisement unregistered.\n");
    }

    /* Unregister the GATT application from BlueZ */
    if (dbus_conn) {
        g_dbus_connection_call_sync(
            dbus_conn,
            BLUEZ_BUS_NAME,
            ADAPTER_PATH,
            GATT_MANAGER_IFACE,
            "UnregisterApplication",
            g_variant_new("(o)", APP_PATH),
            NULL,
            G_DBUS_CALL_FLAGS_NONE,
            -1, NULL, NULL
        );
        printf("[PARMCO] GATT application unregistered.\n");
    }

    /* Unregister the pairing agent from BlueZ */
    if (dbus_conn) {
        g_dbus_connection_call_sync(
            dbus_conn,
            BLUEZ_BUS_NAME,
            "/org/bluez",
            AGENT_MANAGER_IFACE,
            "UnregisterAgent",
            g_variant_new("(o)", AGENT_PATH),
            NULL,
            G_DBUS_CALL_FLAGS_NONE,
            -1, NULL, NULL
        );
        printf("[PARMCO] Pairing agent unregistered.\n");
    }

    /* Unregister D-Bus objects */
    if (agent_reg_id) g_dbus_connection_unregister_object(dbus_conn, agent_reg_id);
    if (adv_reg_id) g_dbus_connection_unregister_object(dbus_conn, adv_reg_id);
    if (tel_reg_id) g_dbus_connection_unregister_object(dbus_conn, tel_reg_id);
    if (cmd_reg_id) g_dbus_connection_unregister_object(dbus_conn, cmd_reg_id);
    if (svc_reg_id) g_dbus_connection_unregister_object(dbus_conn, svc_reg_id);
    if (app_reg_id) g_dbus_connection_unregister_object(dbus_conn, app_reg_id);

    /* Free the main loop */
    if (main_loop) g_main_loop_unref(main_loop);

    printf("[PARMCO] Shutdown complete.\n");
    return EXIT_SUCCESS;
}
