/**
 * BLEConnectionSheet.swift
 * PARMCO — Phone APP RP4 Motor Control
 *
 * ECSE 4235 — Embedded Systems, Spring 2026
 * University of Georgia
 * Authors: Justin Moreno and Jalen Edusei
 *
 * AI Attribution:
 *   This code was AI-Generated by Claude Opus 4.6 (Anthropic).
 *   Prompt engineering and validation by Justin Moreno and Jalen Edusei.
 *
 * Description:
 *   Bottom sheet for BLE connection management. Supports:
 *   - Scanning for PARMCO-RP4 peripherals
 *   - Connecting to a discovered device
 *   - Disconnecting from the current device
 *   - Forgetting the saved connection (clears UserDefaults UUID)
 *     so the user can re-establish from scratch (project requirement:
 *     "If I forget the connection, the phone and RP4 must be able
 *     to reestablish and remember a connection.")
 */

import SwiftUI

struct BLEConnectionSheet: View {
    @ObservedObject var ble: BLEManager
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        VStack(spacing: 0) {
            // MARK: - Header
            HStack {
                Text("Bluetooth Connection")
                    .font(.system(size: 18, weight: .heavy))
                    .foregroundColor(PColor.textPrimary)
                    .tracking(1)
                Spacer()
                Button("Done") { dismiss() }
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(PColor.borderActive)
            }
            .padding(.bottom, 16)

            // MARK: - Status Row
            HStack(spacing: 10) {
                Circle()
                    .fill(ble.connectionState.color)
                    .frame(width: 10, height: 10)
                Text(ble.statusMessage)
                    .font(.system(size: 13))
                    .foregroundColor(PColor.textSecondary)
                    .lineLimit(2)
                Spacer()
            }
            .padding(12)
            .background(PColor.bgCardElevated)
            .cornerRadius(10)
            .padding(.bottom, 14)

            // MARK: - Action Buttons
            VStack(spacing: 8) {
                switch ble.connectionState {
                case .disconnected:
                    Button {
                        ble.startScan()
                    } label: {
                        Text("Scan for PARMCO-RP4")
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                            .background(PColor.borderActive)
                            .cornerRadius(10)
                    }

                case .scanning:
                    Button {
                        ble.stopScan()
                        ble.connectionState = .disconnected
                        ble.statusMessage = "Scan cancelled."
                    } label: {
                        Text("Stop Scan")
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                            .background(PColor.accentWarning)
                            .cornerRadius(10)
                    }

                case .connecting:
                    HStack(spacing: 10) {
                        ProgressView()
                            .tint(PColor.connecting)
                        Text("Establishing connection...")
                            .font(.system(size: 14, weight: .semibold))
                            .foregroundColor(PColor.connecting)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)

                case .connected:
                    Button {
                        ble.disconnect()
                    } label: {
                        Text("Disconnect")
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(.white)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 14)
                            .background(PColor.accentStopped)
                            .cornerRadius(10)
                    }
                }

                // MARK: - Forget Button (project requirement: forget and re-establish)
                // Visible when a saved peripheral exists and we are not mid-scan/connect.
                if ble.hasSavedPeripheral &&
                   (ble.connectionState == .disconnected || ble.connectionState == .connected) {
                    Button {
                        ble.forgetSavedPeripheral()
                    } label: {
                        HStack(spacing: 6) {
                            Image(systemName: "xmark.circle")
                                .font(.system(size: 13))
                            Text("Forget Saved Connection")
                                .font(.system(size: 13, weight: .semibold))
                        }
                        .foregroundColor(PColor.accentWarning)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 12)
                        .background(PColor.accentWarning.opacity(0.1))
                        .cornerRadius(10)
                        .overlay(
                            RoundedRectangle(cornerRadius: 10)
                                .stroke(PColor.accentWarning.opacity(0.3), lineWidth: 1)
                        )
                    }
                }
            }
            .padding(.bottom, 14)

            // MARK: - Discovered Devices
            if !ble.discoveredDevices.isEmpty && ble.connectionState != .connected {
                VStack(alignment: .leading, spacing: 8) {
                    Text("DISCOVERED DEVICES")
                        .font(.system(size: 11, weight: .bold))
                        .foregroundColor(PColor.textMuted)
                        .tracking(2)

                    ForEach(ble.discoveredDevices) { device in
                        Button {
                            ble.connect(to: device)
                            dismiss()
                        } label: {
                            HStack {
                                VStack(alignment: .leading, spacing: 2) {
                                    Text(device.name)
                                        .font(.system(size: 14, weight: .bold))
                                        .foregroundColor(PColor.textPrimary)
                                    Text(device.id.uuidString)
                                        .font(.system(size: 10, design: .monospaced))
                                        .foregroundColor(PColor.textMuted)
                                }
                                Spacer()
                                Text("\(device.rssi) dBm")
                                    .font(.system(size: 11, weight: .semibold))
                                    .foregroundColor(PColor.textSecondary)
                                    .padding(.horizontal, 8)
                                    .padding(.vertical, 4)
                                    .background(PColor.bgCardElevated)
                                    .cornerRadius(6)
                            }
                            .padding(14)
                            .background(PColor.bgPrimary)
                            .cornerRadius(10)
                            .overlay(
                                RoundedRectangle(cornerRadius: 10)
                                    .stroke(PColor.border, lineWidth: 1)
                            )
                        }
                    }
                }
                .padding(.bottom, 12)
            }

            // MARK: - Scanning Indicator
            if ble.connectionState == .scanning {
                HStack(spacing: 8) {
                    ProgressView()
                        .tint(PColor.scanning)
                    Text("Searching for BLE peripherals...")
                        .font(.system(size: 13))
                        .foregroundColor(PColor.scanning)
                }
                .padding(.vertical, 10)
            }

            // MARK: - Help Text
            if ble.connectionState == .disconnected {
                Text("Tap \"Scan\" to search for your Raspberry Pi 4. Make sure the BLE server is running on the RP4 and Bluetooth is enabled on this device.")
                    .font(.system(size: 12))
                    .foregroundColor(PColor.textMuted)
                    .lineSpacing(4)
                    .padding(.top, 6)
            } else if ble.connectionState == .connected {
                Text("To test \"forget and reconnect\": tap Forget Saved Connection above, then go to Settings > Bluetooth, forget PARMCO-RP4, return here, and scan again.")
                    .font(.system(size: 12))
                    .foregroundColor(PColor.textMuted)
                    .lineSpacing(4)
                    .padding(.top, 6)
            }

            Spacer()
        }
        .padding(20)
        .padding(.bottom, 20)
        .background(PColor.bgCard)
    }
}
