/**
 * ContentView.swift
 * PARMCO — Phone APP RP4 Motor Control
 *
 * ECSE 4235 — Embedded Systems, Spring 2026
 * University of Georgia
 * Authors: Justin Moreno and Jalen Edusei
 * Checkpoint: Final — all three control modes live over BLE
 *
 * AI Attribution:
 *   Originally AI-Generated by Claude Opus 4.6 (Anthropic) for CP2.
 *   CP3 edits AI-generated April 15, 2026, directed by Jalen Edusei.
 *   Final edits AI-generated April 20, 2026, directed by Jalen Edusei.
 *
 * Final delta (from CP3):
 *   - Automatic tab is live (was "Coming soon" in CP3).
 *   - New automaticSubmodeSelector row appears under the mode row
 *     when Automatic is active. Maintain / Match are both wired.
 *   - .onChange hooks re-attached: controlMode transitions push
 *     MODE:MANUAL; submode transitions push AUTO:MAINTAIN or
 *     AUTO:MATCH. Gated on .connected so stale taps don't queue.
 *   - rpmCard shows a secondary REF line when in MATCH mode so
 *     the user can see both setpoint and tracking result.
 *   - The modeButton helper is factored out of the old inline
 *     code so Manual/Automatic and Maintain/Match share styling.
 *
 * CP3 delta (kept in place):
 *   - Reconnecting banner pinned above the header whenever the BLE
 *     manager enters .reconnecting.
 *   - Manual-mode Target RPM input is always visible. Sends RPM:<int>.
 */

import SwiftUI

struct ContentView: View {
    @StateObject private var motor = MotorState()
    @StateObject private var ble = BLEManager()
    @State private var showBLESheet = false
    @State private var pulseScale: CGFloat = 1.0
    @State private var circleScale: CGFloat = 1.0

    var body: some View {
        ZStack {
            PColor.bgPrimary.ignoresSafeArea()

            ScrollView(showsIndicators: false) {
                VStack(spacing: 0) {

                    // === HUMAN EDIT START (CP3, Jalen) ===
                    // Reconnecting banner pinned to the top of the scroll
                    // view. Matches the RN build visually.
                    if ble.connectionState == .reconnecting {
                        reconnectBanner
                    }
                    // === HUMAN EDIT END ===

                    headerSection
                    circleIndicator
                    rpmCard
                    speedControl

                    // === HUMAN EDIT START (CP3, Jalen) ===
                    // Target RPM input is now always visible (manual-mode
                    // RPM command per CP3 check sheet).
                    targetRPMInput
                    // === HUMAN EDIT END ===

                    directionAndStartStop
                    modeSelector

                    // === HUMAN EDIT START (Final, Jalen) ===
                    // Submode row appears only when Automatic is active.
                    // Conditional render keeps the layout tight in MANUAL
                    // mode so there's no empty gray band.
                    if motor.controlMode == .automatic {
                        automaticSubmodeSelector
                    }
                    // === HUMAN EDIT END ===
                }
                .padding(.horizontal, 20)
            }
        }
        .preferredColorScheme(.dark)
        .onAppear { ble.motorState = motor }
        .sheet(isPresented: $showBLESheet) {
            BLEConnectionSheet(ble: ble)
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
                .presentationBackground(PColor.bgCard)
        }
        .onChange(of: motor.isRunning) { _, running in
            if running { startPulse() } else { stopPulse() }
        }

        // === HUMAN EDIT START (Final, Jalen) ===
        // Mode-change hooks. Each transition produces exactly one BLE
        // command so the RP4 controller switches in lockstep with the
        // iOS selector. Switching to Automatic sends whichever submode
        // is currently selected (defaults to .maintain on first entry).
        .onChange(of: motor.controlMode) { _, newMode in
            guard ble.connectionState == .connected else { return }
            if newMode == .manual {
                ble.sendCommand("MODE:MANUAL")
            } else {
                ble.sendCommand(motor.automaticSubmode.command)
            }
        }
        .onChange(of: motor.automaticSubmode) { _, newSubmode in
            // Only emit when we're actually in Automatic — tapping the
            // submode pill while Manual is active shouldn't do anything
            // over the wire.
            guard motor.controlMode == .automatic,
                  ble.connectionState == .connected else { return }
            ble.sendCommand(newSubmode.command)
        }
        // === HUMAN EDIT END ===

        // /* === ORIGINAL AI CODE (CP2) — auto-mode wiring removed in CP3 ===
        // .onChange(of: motor.controlMode) { _, newMode in
        //     if newMode == .manual { ble.sendCommand("MODE:MANUAL") }
        //     else { ble.sendCommand(motor.automaticSubmode.command) }
        // }
        // .onChange(of: motor.automaticSubmode) { _, newSubmode in
        //     if motor.controlMode == .automatic { ble.sendCommand(newSubmode.command) }
        // }
        // === END ORIGINAL AI CODE === */
    }

    // MARK: - CP3 Reconnecting Banner
    // === HUMAN EDIT START (CP3, Jalen) ===
    private var reconnectBanner: some View {
        HStack(spacing: 10) {
            ProgressView()
                .progressViewStyle(CircularProgressViewStyle(tint: PColor.textOnAccent))
            Text("Reconnecting to PARMCO-RP4…")
                .font(.system(size: 13, weight: .bold))
                .foregroundColor(PColor.textOnAccent)
                .tracking(0.5)
            Spacer()
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
        .background(PColor.connecting)
        .cornerRadius(12)
        .padding(.top, 8)
        .padding(.bottom, 4)
        .transition(.move(edge: .top).combined(with: .opacity))
    }
    // === HUMAN EDIT END ===

    // MARK: - Header

    private var headerSection: some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                Text("PARMCO")
                    .font(.system(size: 26, weight: .heavy))
                    .foregroundColor(PColor.textPrimary)
                    .tracking(3)
                Text("Motor Control System")
                    .font(.system(size: 12))
                    .foregroundColor(PColor.textMuted)
                    .tracking(1)
            }
            Spacer()
            Button { showBLESheet = true } label: {
                HStack(spacing: 6) {
                    Circle()
                        .fill(ble.connectionState.color)
                        .frame(width: 8, height: 8)
                    Text(ble.connectionState.rawValue)
                        .font(.system(size: 11, weight: .semibold))
                        .foregroundColor(PColor.textSecondary)
                        .tracking(0.5)
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 6)
                .background(PColor.bgCard)
                .cornerRadius(20)
                .overlay(
                    RoundedRectangle(cornerRadius: 20)
                        .stroke(PColor.border, lineWidth: 1)
                )
            }
        }
        .padding(.bottom, 10)
        .padding(.top, 8)
    }

    // MARK: - Circle

    private var circleIndicator: some View {
        VStack(spacing: 8) {
            ZStack {
                Circle()
                    .stroke(motor.circleColor, lineWidth: 3)
                    .frame(width: 208, height: 208)
                Circle()
                    .fill(motor.circleColor)
                    .frame(width: 188, height: 188)
                    .overlay {
                        VStack(spacing: 2) {
                            Text(motor.statusLabel)
                                .font(.system(size: 16, weight: .heavy))
                                .foregroundColor(PColor.textOnAccent)
                                .tracking(3)
                            Text("\(motor.speedPercent)%")
                                .font(.system(size: 32, weight: .light))
                                .foregroundColor(PColor.textOnAccent)
                        }
                    }
            }
            .scaleEffect(pulseScale * circleScale)
            .animation(.easeInOut(duration: 0.15), value: circleScale)

            Text(motor.direction.label)
                .font(.system(size: 12, weight: .bold))
                .foregroundColor(motor.circleColor)
                .tracking(2)
        }
        .padding(.vertical, 10)
    }

    // MARK: - RPM Display

    private var rpmCard: some View {
        VStack(spacing: 2) {
            Text("ACTUAL RPM")
                .font(.system(size: 10, weight: .bold))
                .foregroundColor(PColor.textMuted)
                .tracking(2)
            Text(motor.actualRPM != nil ? "\(motor.actualRPM!)" : "---")
                .font(.system(size: 26, weight: .ultraLight))
                .foregroundColor(motor.actualRPM != nil ? PColor.textPrimary : PColor.textSecondary)
                .tracking(4)

            // === HUMAN EDIT START (Final, Jalen) ===
            // When MATCH is active, surface the reference-RPM reading
            // directly under the actual so the user can see both the
            // setpoint and the tracking result at a glance. Hidden
            // outside MATCH to keep the card uncluttered.
            if motor.controlMode == .automatic,
               motor.automaticSubmode == .match {
                HStack(spacing: 6) {
                    Text("REF")
                        .font(.system(size: 9, weight: .bold))
                        .foregroundColor(PColor.textMuted)
                        .tracking(1.5)
                    Text(motor.referenceRPM != nil ? "\(motor.referenceRPM!)" : "---")
                        .font(.system(size: 14, weight: .medium, design: .monospaced))
                        .foregroundColor(PColor.textSecondary)
                }
                .padding(.top, 2)
            }
            // === HUMAN EDIT END ===

            // === HUMAN EDIT START (CP3, Jalen) ===
            Text(ble.connectionState == .connected
                 ? "Live telemetry from RP4"
                 : ble.connectionState == .reconnecting
                    ? "Paused — reconnecting"
                    : "Connect to RP4 for live data")
                .font(.system(size: 10))
                .foregroundColor(PColor.textMuted)
                .italic()
            // === HUMAN EDIT END ===
        }
        .frame(maxWidth: .infinity)
        .padding(10)
        .background(PColor.bgCard)
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(PColor.border, lineWidth: 1)
        )
        .padding(.bottom, 8)
    }

    // MARK: - Speed Control

    private var speedControl: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("SPEED")
                    .font(.system(size: 10, weight: .bold))
                    .foregroundColor(PColor.textMuted)
                    .tracking(2)
                Spacer()
            }
            HStack(spacing: 12) {
                Button {
                    motor.adjustSpeed(by: -10)
                    ble.sendCommand("SPD:\(motor.speedPercent)")
                } label: {
                    Text("-")
                        .font(.system(size: 22))
                        .foregroundColor(PColor.textPrimary)
                        .frame(width: 44, height: 44)
                        .background(PColor.buttonActive)
                        .clipShape(Circle())
                        .overlay(Circle().stroke(PColor.border, lineWidth: 1))
                }
                .disabled(motor.speedPercent <= 0)
                .opacity(motor.speedPercent <= 0 ? 0.35 : 1)

                GeometryReader { geo in
                    ZStack(alignment: .leading) {
                        RoundedRectangle(cornerRadius: 16).fill(PColor.bgInput)
                        RoundedRectangle(cornerRadius: 16)
                            .fill(motor.speedPercent > 80
                                  ? PColor.accentWarning
                                  : PColor.accentSpeed)
                            .frame(width: geo.size.width * CGFloat(motor.speedPercent) / 100.0)
                            .animation(.easeOut(duration: 0.2), value: motor.speedPercent)
                        Text("\(motor.speedPercent)%")
                            .font(.system(size: 13, weight: .bold))
                            .foregroundColor(PColor.textPrimary)
                            .tracking(1)
                            .frame(maxWidth: .infinity)
                    }
                }
                .frame(height: 32)

                Button {
                    motor.adjustSpeed(by: 10)
                    ble.sendCommand("SPD:\(motor.speedPercent)")
                } label: {
                    Text("+")
                        .font(.system(size: 22))
                        .foregroundColor(PColor.textPrimary)
                        .frame(width: 44, height: 44)
                        .background(PColor.buttonActive)
                        .clipShape(Circle())
                        .overlay(Circle().stroke(PColor.border, lineWidth: 1))
                }
                .disabled(motor.speedPercent >= 100)
                .opacity(motor.speedPercent >= 100 ? 0.35 : 1)
            }
        }
        .padding(12)
        .background(PColor.bgCard)
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(PColor.border, lineWidth: 1)
        )
        .padding(.bottom, 10)
    }

    // MARK: - CP3 Target RPM Input
    // === HUMAN EDIT START (CP3, Jalen) ===
    /// CP3: Target RPM input is always visible in manual mode and sends
    /// RPM:<int> on Set. Renamed from "DESIRED RPM" so the label matches
    /// the CP3 check sheet vocabulary.
    private var targetRPMInput: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("TARGET RPM")
                .font(.system(size: 10, weight: .bold))
                .foregroundColor(PColor.textMuted)
                .tracking(2)

            HStack(spacing: 10) {
                TextField("e.g. 4500", text: $motor.targetRPM)
                    .keyboardType(.numberPad)
                    .font(.system(size: 18, weight: .semibold, design: .monospaced))
                    .foregroundColor(PColor.textPrimary)
                    .padding(.horizontal, 14)
                    .padding(.vertical, 10)
                    .background(PColor.bgInput)
                    .cornerRadius(10)
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .stroke(PColor.border, lineWidth: 1)
                    )

                Button {
                    if let rpm = motor.targetRPMValue {
                        ble.setTargetRPM(rpm)
                    }
                } label: {
                    Text("SET")
                        .font(.system(size: 13, weight: .heavy))
                        .tracking(1.5)
                        .foregroundColor(PColor.textOnAccent)
                        .padding(.horizontal, 20)
                        .padding(.vertical, 12)
                        .background(
                            (motor.targetRPMValue != nil && ble.connectionState == .connected)
                            ? PColor.accentSpeed
                            : PColor.accentIdle
                        )
                        .cornerRadius(10)
                }
                .disabled(motor.targetRPMValue == nil || ble.connectionState != .connected)
            }

            if ble.connectionState != .connected {
                Text("Connect to RP4 to send RPM setpoint")
                    .font(.system(size: 10))
                    .foregroundColor(PColor.textMuted)
                    .italic()
            }
        }
        .padding(12)
        .background(PColor.bgCard)
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(PColor.border, lineWidth: 1)
        )
        .padding(.bottom, 10)
    }
    // === HUMAN EDIT END ===

    // MARK: - Direction & Start/Stop

    private var directionAndStartStop: some View {
        HStack(spacing: 12) {
            directionButton(direction: .forward, icon: "↻",
                isActive: motor.direction == .forward,
                activeColor: PColor.accentForward)

            Button {
                bumpCircle()
                motor.isRunning.toggle()
                ble.sendCommand(motor.isRunning ? "START" : "STOP")
            } label: {
                VStack(spacing: 2) {
                    Text(motor.isRunning ? "◼" : "▶")
                        .font(.system(size: 18))
                        .foregroundColor(PColor.textOnAccent)
                    Text(motor.isRunning ? "STOP" : "START")
                        .font(.system(size: 9, weight: .heavy))
                        .foregroundColor(PColor.textOnAccent)
                        .tracking(2)
                }
                .frame(width: 72, height: 72)
                .background(motor.isRunning ? PColor.accentStopped : PColor.accentForward)
                .clipShape(Circle())
                .shadow(color: .black.opacity(0.4), radius: 8, y: 4)
            }

            directionButton(direction: .reverse, icon: "↺",
                isActive: motor.direction == .reverse,
                activeColor: PColor.accentReverse)
        }
        .padding(.bottom, 10)
    }

    private func directionButton(
        direction: MotorDirection,
        icon: String,
        isActive: Bool,
        activeColor: Color
    ) -> some View {
        Button {
            guard motor.direction != direction else { return }
            bumpCircle()
            motor.direction = direction
            ble.sendCommand(direction.rawValue)
        } label: {
            VStack(spacing: 2) {
                Text(icon).font(.system(size: 20))
                    .foregroundColor(PColor.textSecondary)
                Text(direction == .forward ? "Forward" : "Reverse")
                    .font(.system(size: 11, weight: .bold))
                    .foregroundColor(isActive ? PColor.textPrimary : PColor.textSecondary)
                    .tracking(1)
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, 12)
            .background(isActive ? activeColor.opacity(0.1) : PColor.bgCard)
            .cornerRadius(14)
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .stroke(isActive ? activeColor : PColor.border, lineWidth: 1)
            )
        }
    }

    // MARK: - Mode Selector (Final: both tabs live)

    // /* === ORIGINAL AI CODE (CP2) — both tabs fully active ===
    // private var modeSelector: some View {
    //     HStack(spacing: 4) {
    //         ForEach(ControlMode.allCases, id: \.self) { mode in
    //             Button { motor.controlMode = mode } label: { Text(mode.label) ... }
    //         }
    //     }
    // }
    // === END ORIGINAL AI CODE === */

    // === HUMAN EDIT START (Final, Jalen) ===
    // Both tabs are now live. CP3 had Automatic disabled with a
    // "Coming soon" label because the closed-loop controllers weren't
    // integrated into the BLE server yet. In the final build the RP4
    // runs the MAINTAIN and MATCH controllers itself and the iOS side
    // just picks which one is active via a MODE: command.
    private var modeSelector: some View {
        HStack(spacing: 4) {
            modeButton(title: "Manual", isActive: motor.controlMode == .manual) {
                motor.controlMode = .manual
            }
            modeButton(title: "Automatic", isActive: motor.controlMode == .automatic) {
                motor.controlMode = .automatic
            }
        }
        .padding(4)
        .background(PColor.bgCard)
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(PColor.border, lineWidth: 1)
        )
        .padding(.bottom, 12)
    }

    /// Shared segmented-pill button used by both the mode and submode
    /// selectors. Factored out so the two rows match pixel-for-pixel.
    private func modeButton(
        title: String,
        isActive: Bool,
        action: @escaping () -> Void
    ) -> some View {
        Button {
            withAnimation(.easeInOut(duration: 0.2)) { action() }
        } label: {
            Text(title)
                .font(.system(size: 12, weight: .bold))
                .foregroundColor(isActive ? PColor.textPrimary : PColor.textMuted)
                .tracking(1)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 10)
                .background(isActive ? PColor.bgCardElevated : Color.clear)
                .cornerRadius(10)
                .overlay(
                    RoundedRectangle(cornerRadius: 10)
                        .stroke(isActive ? PColor.borderActive : Color.clear, lineWidth: 1)
                )
        }
    }

    /// Submode selector shown only when controlMode == .automatic.
    /// Writes AUTO:MAINTAIN or AUTO:MATCH on tap via the .onChange
    /// hook attached to the main ScrollView.
    private var automaticSubmodeSelector: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("AUTOMATIC SUBMODE")
                .font(.system(size: 10, weight: .bold))
                .foregroundColor(PColor.textMuted)
                .tracking(2)

            HStack(spacing: 4) {
                modeButton(
                    title: "Maintain",
                    isActive: motor.automaticSubmode == .maintain
                ) { motor.automaticSubmode = .maintain }
                modeButton(
                    title: "Match",
                    isActive: motor.automaticSubmode == .match
                ) { motor.automaticSubmode = .match }
            }

            // Inline hint that swaps based on which submode is active.
            // Keeps the user oriented without a modal or help sheet.
            Text(motor.automaticSubmode == .maintain
                 ? "Holding Target RPM using the motor's IR sensor."
                 : "Matching the reference source on GPIO23.")
                .font(.system(size: 10))
                .foregroundColor(PColor.textMuted)
                .italic()
        }
        .padding(12)
        .background(PColor.bgCard)
        .cornerRadius(14)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(PColor.border, lineWidth: 1)
        )
        .padding(.bottom, 10)
    }
    // === HUMAN EDIT END ===

    // MARK: - Animations

    private func bumpCircle() {
        circleScale = 0.92
        withAnimation(.spring(response: 0.25, dampingFraction: 0.5)) {
            circleScale = 1.0
        }
    }
    private func startPulse() {
        withAnimation(.easeInOut(duration: 0.8).repeatForever(autoreverses: true)) {
            pulseScale = 1.06
        }
    }
    private func stopPulse() {
        withAnimation(.easeOut(duration: 0.3)) { pulseScale = 1.0 }
    }
}

#Preview {
    ContentView()
}
