/**
 * ============================================================================
 * PARMCO — Phone APP RP4 Motor Control — Keyboard Motor Controller
 * ============================================================================
 *
 * File:        motor_control.c
 * Project:     PARMCO (Phone APP RP4 Motor Control)
 * Course:      ECSE 4235 — Embedded Systems, Spring 2026
 * University:  University of Georgia
 * Authors:     Justin Moreno and Jalen Edusei
 * Date:        April 1, 2026
 * Checkpoint:  3 — RP4 motor control via L293D dual motor driver IC
 *
 * Description:
 *   Standalone motor control program for the Raspberry Pi 4. Accepts
 *   keyboard commands in real-time (non-blocking) to control a 12V DC
 *   motor's direction, speed, and on/off state through an L293D dual
 *   H-bridge motor driver IC.
 *
 *   HARDWARE CHANGE FROM CP2:
 *   The CP2 circuit used a custom low-side switching topology (4N25
 *   optocoupler → 2N3906 PNP BJT → IRFZ34 N-MOSFET) which could only
 *   drive the motor in one direction. Direction was a software-only
 *   state variable with no physical effect.
 *
 *   This revision replaces that entire driver stage with a Texas
 *   Instruments L293D quadruple half-H driver IC. The L293D contains
 *   two independent full H-bridge channels, each capable of driving a
 *   motor bidirectionally. By toggling the In1/In2 logic inputs, the
 *   motor's physical rotation direction is now fully reversible in
 *   hardware — the 'w' and 's' keys produce real clockwise and
 *   counterclockwise rotation.
 *
 *   The program uses three layers of hardware interaction:
 *     1. POSIX termios + select() for non-blocking keyboard input
 *     2. ARMv8 assembly (gpio_asm.s) for direct GPIO register manipulation
 *     3. pigpio library for DMA-based hardware PWM on GPIO18 (L293D Enable)
 *
 * AI Attribution:
 *   This code was AI-Generated by Claude Opus 4.6 (Anthropic) on April 1, 2026.
 *   Prompt engineering and validation by Justin Moreno and Jalen Edusei.
 *
 * ============================================================================
 * LIBRARY ATTRIBUTION — pigpio
 * ============================================================================
 *
 *   Library:     pigpio
 *   Author:      joan@abyz.me.uk
 *   Website:     https://abyz.me.uk/rpi/pigpio/
 *   GitHub:      https://github.com/joan2937/pigpio
 *   License:     Unlicense (public domain)
 *
 *   Purpose:
 *     pigpio provides DMA-based hardware-timed PWM on the Raspberry Pi.
 *     Unlike software PWM loops (which use usleep() or busy-wait timing
 *     in user-space), pigpio programs the RP4's Direct Memory Access (DMA)
 *     controller to stream pre-calculated waveform data directly to the
 *     GPIO registers. This happens entirely independently of the CPU —
 *     the DMA engine reads from a circular buffer and toggles pins at
 *     precise microsecond intervals, regardless of what the CPU is doing.
 *
 *   Why it is needed:
 *     The Linux kernel is a preemptive multitasking operating system. It
 *     does NOT provide real-time scheduling guarantees to user-space
 *     processes. The kernel scheduler can (and does) preempt any process
 *     at any time to service interrupts, run other processes, or perform
 *     housekeeping. If PWM timing relied on software delays (e.g.,
 *     usleep(500) to toggle a pin every 500 microseconds), the scheduler
 *     would introduce unpredictable jitter ranging from microseconds to
 *     milliseconds. This jitter manifests as:
 *       - Erratic motor speed fluctuations
 *       - Audible whining or buzzing from the motor
 *       - Jerky acceleration and deceleration
 *     pigpio eliminates all of this by offloading timing to hardware. The
 *     DMA controller maintains perfectly stable PWM frequencies (default
 *     800 Hz with 250 steps) across all GPIO pins, regardless of CPU load.
 *
 *   Installation:
 *     sudo apt install pigpio
 *
 *   Note: pigpio requires root privileges because it directly accesses
 *   the DMA controller and GPIO memory. The program must be run with sudo.
 *
 * ============================================================================
 * HARDWARE ATTRIBUTION — L293D Quadruple Half-H Driver
 * ============================================================================
 *
 *   IC:          L293D (Texas Instruments)
 *   Datasheet:   https://www.ti.com/lit/ds/symlink/l293d.pdf
 *   Package:     16-pin DIP
 *
 *   Purpose:
 *     The L293D is a monolithic integrated circuit containing four
 *     half-H drivers. Two half-H drivers are combined internally to
 *     form one full H-bridge channel, giving two independent full
 *     H-bridge outputs. Each channel can drive a DC motor bidirectionally
 *     with currents up to 600mA (1.2A peak). The IC includes built-in
 *     output clamp diodes for inductive transient suppression, eliminating
 *     the need for external flyback diodes (the 'D' suffix denotes the
 *     diode-protected variant).
 *
 *   Why it replaces the custom MOSFET circuit:
 *     The CP2 low-side switching topology (4N25 → 2N3906 → IRFZ34) could
 *     only conduct current through the motor in one direction. Reversing
 *     direction required either a DPDT relay or a second MOSFET channel
 *     configured as a discrete H-bridge — both adding complexity and parts.
 *     The L293D integrates the entire H-bridge, gate drivers, and flyback
 *     protection into a single 16-pin DIP package. It accepts 3.3V logic
 *     inputs directly (V_IH = 2.3V for VCC1 = 5V), so no optocoupler or
 *     level-shifting is required between the RP4 and the driver IC.
 *
 *   Pin Usage (Channel 1):
 *     Pin 1  (1,2EN)  — Enable: connected to GPIO18 (PWM). When HIGH,
 *                        the H-bridge outputs follow In1/In2 logic.
 *                        When LOW, outputs are high-impedance (motor coasts).
 *                        PWM on this pin modulates motor speed.
 *     Pin 2  (1A/In1) — Input 1: connected to GPIO20. Logic HIGH drives
 *                        Output 1 (pin 3) HIGH.
 *     Pin 3  (1Y)     — Output 1: connected to Motor terminal A.
 *     Pin 6  (2Y)     — Output 2: connected to Motor terminal B.
 *     Pin 7  (2A/In2) — Input 2: connected to GPIO21. Logic HIGH drives
 *                        Output 2 (pin 6) HIGH.
 *     Pin 8  (VCC2)   — Motor supply: connected to +12V external supply.
 *     Pin 16 (VCC1)   — Logic supply: connected to +5V (RP4 5V pin or
 *                        external 5V regulator).
 *     Pins 4,5,12,13 (GND) — All four ground pins must be connected to
 *                        common ground. These also serve as the heat sink
 *                        connection on the PCB.
 *
 *   Direction Truth Table:
 *     In1 (GPIO20) | In2 (GPIO21) | Motor Action
 *     -------------|--------------|------------------
 *          HIGH     |     LOW      | Forward (CW)
 *          LOW      |     HIGH     | Reverse (CCW)
 *          LOW      |     LOW      | Brake (low-side)
 *          HIGH     |     HIGH     | Brake (high-side)
 *
 *   Enable (GPIO18) PWM modulates the effective voltage:
 *     duty_cycle% of VCC2 appears across the motor terminals.
 *     At 50% duty on Enable with In1=H/In2=L, the motor receives
 *     approximately 6V average (50% of 12V).
 *
 * ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>
#include <termios.h>
#include <sys/select.h>
#include <sys/mman.h>

/* pigpio library header — provides gpioInitialise(), gpioPWM(), etc. */
#include <pigpio.h>

/* ============================================================================
 * HARDWARE CONSTANTS
 * ============================================================================ */

/** BCM2711 GPIO peripheral physical base address.
 *  On the RP4, the peripheral address space starts at 0xFE000000.
 *  GPIO registers are at offset 0x200000 from the peripheral base. */
#define GPIO_PHYS_BASE   0xFE200000

/** Size of the GPIO register block to map (one 4KB page is sufficient
 *  to cover all registers from GPFSEL0 through GPLEV1). */
#define GPIO_MAP_SIZE    0x1000

/* ----------------------------------------------------------------------------
 * L293D Pin Mapping (Channel 1)
 * ---------------------------------------------------------------------------- */

/** L293D Enable pin (1,2EN) — connected to GPIO18.
 *  GPIO18 supports hardware PWM (ALT5 = PWM0). The PWM duty cycle on
 *  this pin controls the motor's speed by gating the H-bridge output
 *  drivers. When Enable is LOW, both outputs go high-impedance and the
 *  motor coasts regardless of In1/In2 state. */
#define PIN_ENABLE       18

/** L293D Input 1 (1A) — connected to GPIO20.
 *  Combined with In2, this determines motor direction per the H-bridge
 *  truth table. For forward (CW) rotation: In1=HIGH, In2=LOW. */
#define PIN_IN1          20

/** L293D Input 2 (2A) — connected to GPIO21.
 *  For reverse (CCW) rotation: In1=LOW, In2=HIGH.
 *  For braking: In1=In2 (both HIGH or both LOW). */
#define PIN_IN2          21

/* === ORIGINAL AI CODE (CP2) — kept per course documentation rules ===
 * // #define PIN_PWM          18    // MOSFET gate via optocoupler
 * // #define PIN_DIR          17    // Direction indicator (software only)
 * === END ORIGINAL AI CODE === */

/** Speed adjustment step size (percentage points per keypress). */
#define SPEED_STEP       10

/** Maximum duty cycle value for pigpio's gpioPWM() function.
 *  The default range is 0-255 (8-bit resolution). */
#define PWM_MAX_DUTY     255

/** Main loop polling interval in microseconds.
 *  50ms gives ~20 Hz keyboard polling — responsive enough for human
 *  input without wasting CPU cycles in a tight spin loop. */
#define LOOP_DELAY_US    50000

/* ============================================================================
 * ASSEMBLY FUNCTION DECLARATIONS
 * ============================================================================
 * These functions are defined in gpio_asm.s and linked at compile time.
 * The 'extern' keyword tells the C compiler that the definitions exist
 * in another translation unit. The linker resolves the symbols. */

/** Store the mmap'd GPIO base address for subsequent assembly calls. */
extern void gpio_init(volatile void *base_ptr);

/** Configure a GPIO pin as an output (sets 3-bit field in GPFSEL). */
extern void gpio_set_output(unsigned int pin);

/** Drive a GPIO pin HIGH (value=1) or LOW (value=0) via GPSET0/GPCLR0. */
extern void gpio_write(unsigned int pin, unsigned int value);

/* ============================================================================
 * MOTOR STATE — Global variables
 * ============================================================================ */

/** Motor direction: 1 = forward (clockwise), 0 = reverse (counterclockwise).
 *  With the L293D H-bridge, this directly controls physical rotation:
 *    direction=1 → In1=HIGH, In2=LOW  → current flows A→motor→B (CW)
 *    direction=0 → In1=LOW,  In2=HIGH → current flows B→motor→A (CCW) */
static int motor_direction = 1;

/** Motor speed as a percentage (0–100). Mapped to PWM duty cycle on Enable. */
static int motor_speed = 0;

/** Motor running state: 1 = on, 0 = off. When off, PWM duty = 0
 *  (Enable goes LOW, H-bridge outputs go high-impedance, motor coasts). */
static int motor_running = 0;

/* ============================================================================
 * TERMINAL STATE — for raw mode / restore
 * ============================================================================ */

/** Original terminal settings, saved before entering raw mode.
 *  Restored on exit via atexit() to prevent leaving the terminal broken. */
static struct termios orig_termios;

/** Flag indicating whether we've saved the original terminal state.
 *  Prevents double-restore if cleanup is called multiple times. */
static int termios_saved = 0;

/** Flag for clean shutdown from signal handler. */
static volatile int quit_requested = 0;

/* ============================================================================
 * TERMINAL FUNCTIONS — Raw mode and non-blocking keyboard input
 * ============================================================================ */

/**
 * restore_terminal — restores the terminal to its original settings.
 *
 * Called automatically by atexit() when the program exits (normally or
 * via exit()). This is CRITICAL: if the terminal is left in raw mode,
 * the user's shell becomes unusable (no echo, no line editing, no Ctrl+C).
 */
static void restore_terminal(void)
{
    if (termios_saved) {
        /* TCSANOW applies the change immediately, without waiting for
         * pending output to drain. This ensures cleanup even on crashes. */
        tcsetattr(STDIN_FILENO, TCSANOW, &orig_termios);
        termios_saved = 0;
        printf("\n[PARMCO] Terminal restored.\n");
    }
}

/**
 * set_raw_mode — switches the terminal to raw, non-echoing mode.
 *
 * In raw mode:
 *   - Characters are available to read() immediately (no Enter needed)
 *   - Typed characters are not echoed to the screen
 *   - Special characters (Ctrl+C, Ctrl+Z) are not processed by the terminal
 *
 * This is necessary for real-time keyboard control of the motor. In
 * canonical mode (the default), the terminal buffers entire lines and
 * only delivers them when the user presses Enter — completely unusable
 * for interactive motor control.
 */
static void set_raw_mode(void)
{
    struct termios raw;

    /* Save the current terminal settings so we can restore them later.
     * tcgetattr() populates the termios struct with the current config. */
    if (tcgetattr(STDIN_FILENO, &orig_termios) < 0) {
        perror("[PARMCO] tcgetattr failed");
        exit(EXIT_FAILURE);
    }
    termios_saved = 1;

    /* Register the restore function to run on ANY exit path.
     * atexit() handlers run for normal exit(), return from main(), and
     * some abnormal terminations. Signal handlers cover SIGINT/SIGTERM. */
    atexit(restore_terminal);

    /* Copy the original settings and modify the copy. */
    raw = orig_termios;

    /* c_lflag controls "local" (terminal-side) processing.
     *
     * ICANON (canonical mode): when set, the terminal buffers input
     *   line-by-line and only delivers complete lines to read().
     *   Clearing it enables character-at-a-time input.
     *
     * ECHO: when set, typed characters are displayed on screen.
     *   Clearing it prevents keystrokes from cluttering our status output.
     *
     * The ~(ICANON | ECHO) expression creates a bitmask with those two
     * bits cleared, and &= applies it without affecting other flags. */
    raw.c_lflag &= ~(ICANON | ECHO);

    /* c_cc[VMIN] = minimum number of characters for read() to return.
     * Setting it to 0 means read() returns immediately even if no data
     * is available (non-blocking when combined with select()). */
    raw.c_cc[VMIN] = 0;

    /* c_cc[VTIME] = read timeout in tenths of a second.
     * Setting it to 0 means no timeout — read() returns immediately. */
    raw.c_cc[VTIME] = 0;

    /* Apply the modified settings immediately (TCSANOW). */
    if (tcsetattr(STDIN_FILENO, TCSANOW, &raw) < 0) {
        perror("[PARMCO] tcsetattr failed");
        exit(EXIT_FAILURE);
    }
}

/**
 * kbhit — checks if a keypress is waiting in the input buffer.
 *
 * Uses the select() system call with a zero timeout to poll the stdin
 * file descriptor without blocking. select() examines a set of file
 * descriptors and reports which ones are ready for I/O.
 *
 * With a zero timeout (both tv_sec and tv_usec = 0), select() checks
 * the buffer state and returns immediately:
 *   - Returns > 0 if data is available to read
 *   - Returns 0 if the buffer is empty
 *   - Returns -1 on error
 *
 * @return 1 if a key is available, 0 if not.
 */
static int kbhit(void)
{
    fd_set read_fds;
    struct timeval timeout;

    /* Zero the file descriptor set, then add stdin (fd 0) to it.
     * FD_ZERO clears all bits. FD_SET sets the bit for STDIN_FILENO. */
    FD_ZERO(&read_fds);
    FD_SET(STDIN_FILENO, &read_fds);

    /* Set timeout to zero — makes select() non-blocking.
     * It will check the buffer and return immediately. */
    timeout.tv_sec = 0;
    timeout.tv_usec = 0;

    /* select() arguments:
     *   nfds = STDIN_FILENO + 1 (one past the highest fd in the set)
     *   readfds = our set containing stdin
     *   writefds = NULL (we don't care about write readiness)
     *   exceptfds = NULL (we don't care about exceptions)
     *   timeout = 0 seconds, 0 microseconds (poll and return) */
    return select(STDIN_FILENO + 1, &read_fds, NULL, NULL, &timeout) > 0;
}

/**
 * read_key — reads a single character from stdin.
 *
 * Should only be called after kbhit() returns 1, guaranteeing that
 * data is available. In raw mode with VMIN=0, read() will return
 * immediately with 0 bytes if the buffer is empty.
 *
 * @return the character read, or -1 if read failed.
 */
static int read_key(void)
{
    char c;
    if (read(STDIN_FILENO, &c, 1) == 1) {
        return (int)c;
    }
    return -1;
}

/* ============================================================================
 * GPIO MEMORY MAPPING
 * ============================================================================ */

/**
 * map_gpio — maps the BCM2711 GPIO registers into user-space virtual memory.
 *
 * The BCM2711's GPIO control registers exist at physical address 0xFE200000.
 * User-space programs cannot access physical memory directly — the MMU
 * translates virtual addresses to physical addresses, and kernel-reserved
 * physical pages are not mapped into user-space page tables.
 *
 * /dev/gpiomem is a character device that allows user-space programs to
 * mmap() the GPIO register page specifically. Unlike /dev/mem (which maps
 * ALL physical memory and requires root), /dev/gpiomem maps only the GPIO
 * block and can be used by non-root users who are in the 'gpio' group.
 * However, since we also use pigpio (which requires root for DMA access),
 * we run as root anyway.
 *
 * mmap() returns a pointer to the virtual address where the GPIO registers
 * are mapped. This pointer is passed to our assembly functions via gpio_init().
 *
 * @return a volatile pointer to the mapped GPIO registers, or exits on failure.
 */
static volatile void *map_gpio(void)
{
    int fd;
    volatile void *gpio_map;

    /* Open the GPIO memory device.
     * O_RDWR = read/write access (we need to write to GPFSEL, GPSET, GPCLR).
     * O_SYNC = disable caching (GPIO registers must not be cached — writes
     *          must go directly to the hardware). */
    fd = open("/dev/gpiomem", O_RDWR | O_SYNC);
    if (fd < 0) {
        perror("[PARMCO] Failed to open /dev/gpiomem");
        fprintf(stderr, "Make sure you are running as root (sudo).\n");
        exit(EXIT_FAILURE);
    }

    /* Map the GPIO register page into our virtual address space.
     *
     * Arguments:
     *   NULL       — let the kernel choose the virtual address
     *   GPIO_MAP_SIZE — map 4096 bytes (one page, covers all GPIO registers)
     *   PROT_READ | PROT_WRITE — we need both read and write access
     *   MAP_SHARED — changes are visible to other processes and to hardware
     *   fd         — the /dev/gpiomem file descriptor
     *   0          — offset within /dev/gpiomem (0 = start of GPIO block)
     *
     * Returns MAP_FAILED on error. */
    gpio_map = mmap(NULL, GPIO_MAP_SIZE, PROT_READ | PROT_WRITE,
                    MAP_SHARED, fd, 0);

    /* Close the file descriptor — the mapping persists after close(). */
    close(fd);

    if (gpio_map == MAP_FAILED) {
        perror("[PARMCO] mmap failed");
        exit(EXIT_FAILURE);
    }

    return gpio_map;
}

/* ============================================================================
 * STATUS DISPLAY
 * ============================================================================ */

/**
 * print_status — prints the current motor state as a formatted status line.
 *
 * Uses carriage return (\r) to overwrite the current line, providing a
 * clean, non-scrolling display. The \033[K ANSI escape code erases from
 * the cursor to the end of the line, preventing artifacts from shorter
 * status strings overwriting longer ones.
 */
static void print_status(void)
{
    const char *dir_str = motor_direction ? "FORWARD (CW) " : "REVERSE (CCW)";
    const char *run_str = motor_running   ? "ON " : "OFF";

    /* \r   = carriage return (move cursor to start of line)
     * \033[K = ANSI escape: erase from cursor to end of line */
    printf("\r\033[K  [%s]  Direction: %s  |  Speed: %3d%%  |  Motor: %s  ",
           motor_running ? ">>>" : "---",
           dir_str, motor_speed, run_str);
    fflush(stdout);
}

/* ============================================================================
 * PWM UPDATE
 * ============================================================================ */

/**
 * update_pwm — sets the PWM duty cycle on the L293D Enable pin.
 *
 * When the motor is off (motor_running == 0), the Enable duty cycle is
 * set to 0. With Enable LOW, the L293D's output drivers enter a
 * high-impedance state — both Output 1 and Output 2 float, and the
 * motor coasts to a stop (no active braking).
 *
 * When the motor is on, the speed percentage (0–100) is linearly mapped
 * to the pigpio duty cycle range (0–255) on the Enable pin:
 *   0%   → duty = 0   (Enable always LOW, outputs high-Z, motor coasts)
 *   50%  → duty = 127 (Enable toggling at 50% duty, ~6V average to motor)
 *   100% → duty = 255 (Enable always HIGH, full 12V across motor)
 *
 * The In1/In2 direction pins remain static during PWM — they set the
 * current path through the H-bridge, while Enable gates the output
 * transistors on and off at the PWM frequency.
 */
static void update_pwm(void)
{
    int duty;

    if (motor_running && motor_speed > 0) {
        /* Map percentage to 0–255 range */
        duty = (motor_speed * PWM_MAX_DUTY) / 100;
    } else {
        duty = 0;
    }

    /* gpioPWM() sets the PWM duty cycle on the Enable pin.
     * pigpio handles the DMA-based timing internally — we just provide
     * the duty cycle value and it maintains the waveform. */
    gpioPWM(PIN_ENABLE, duty);
}

/* ============================================================================
 * DIRECTION UPDATE — L293D H-Bridge Logic
 * ============================================================================ */

/**
 * update_direction — sets the L293D In1/In2 pins for the desired direction.
 *
 * The L293D H-bridge reverses motor polarity by swapping which output
 * is driven HIGH vs LOW. The internal structure contains four transistors
 * (two per output) arranged so that:
 *
 *   In1=HIGH, In2=LOW:
 *     Output 1 sources current (HIGH-side transistor ON)
 *     Output 2 sinks current (LOW-side transistor ON)
 *     Current path: VCC2 → Output 1 → Motor → Output 2 → GND
 *     Result: Motor spins clockwise (FORWARD)
 *
 *   In1=LOW, In2=HIGH:
 *     Output 1 sinks current (LOW-side transistor ON)
 *     Output 2 sources current (HIGH-side transistor ON)
 *     Current path: VCC2 → Output 2 → Motor → Output 1 → GND
 *     Result: Motor spins counterclockwise (REVERSE)
 *
 * The direction can be changed while the motor is spinning. The L293D
 * handles the transition safely — the internal cross-conduction
 * protection prevents shoot-through during switching. However, an
 * instant polarity reversal under full speed subjects the motor and
 * gearbox to high mechanical stress. For smoother reversals, ramp the
 * speed down to 0, change direction, then ramp back up.
 *
 * Uses the assembly gpio_write() function for atomic pin control.
 * gpio_write() accesses GPSET0/GPCLR0 registers which are write-only
 * and bit-atomic — no read-modify-write race condition.
 */
static void update_direction(void)
{
    if (motor_direction) {
        /* FORWARD: In1 = HIGH, In2 = LOW */
        gpio_write(PIN_IN1, 1);
        gpio_write(PIN_IN2, 0);
    } else {
        /* REVERSE: In1 = LOW, In2 = HIGH */
        gpio_write(PIN_IN1, 0);
        gpio_write(PIN_IN2, 1);
    }
}

/* ============================================================================
 * SIGNAL HANDLER — Clean shutdown on Ctrl+C
 * ============================================================================ */

/**
 * signal_handler — catches SIGINT (Ctrl+C) and SIGTERM for clean shutdown.
 *
 * Rather than calling cleanup functions directly from the handler (which
 * is unsafe for non-async-signal-safe functions like printf), we set a
 * flag that the main loop checks on each iteration.
 */
static void signal_handler(int signum)
{
    (void)signum;
    quit_requested = 1;
}

/* ============================================================================
 * CLEANUP
 * ============================================================================ */

/**
 * cleanup — stops the motor, terminates pigpio, and restores the terminal.
 *
 * Called on normal exit ('q' key) and on signal-triggered shutdown.
 * The shutdown sequence is:
 *   1. Set Enable PWM duty to 0 (outputs go high-impedance, motor coasts)
 *   2. Set In1 and In2 both LOW (both low-side transistors off — clean state)
 *   3. Terminate pigpio (releases DMA channel and GPIO mappings)
 *   4. Terminal restoration happens via atexit(restore_terminal)
 */
static void cleanup(void)
{
    printf("\n\n[PARMCO] Shutting down...\n");

    /* Stop the motor by setting Enable PWM duty to 0.
     * With Enable LOW, the L293D output drivers enter high-impedance
     * state and the motor coasts to a stop. */
    gpioPWM(PIN_ENABLE, 0);
    printf("[PARMCO] Motor stopped (Enable PWM duty = 0).\n");

    /* Set both direction inputs LOW — clean idle state.
     * Both In1=LOW and In2=LOW = both low-side transistors engage,
     * shorting the motor terminals through the low-side path = brake.
     * However, since Enable is already LOW (high-Z), the brake has
     * no effect — the motor simply coasts. This is just good practice
     * to leave the pins in a known, safe state. */
    gpio_write(PIN_IN1, 0);
    gpio_write(PIN_IN2, 0);
    printf("[PARMCO] Direction pins cleared (In1=LOW, In2=LOW).\n");

    /* Terminate the pigpio library.
     * This releases the DMA channel, stops all PWM outputs, and frees
     * the memory-mapped register pages used internally by pigpio. */
    gpioTerminate();
    printf("[PARMCO] pigpio terminated.\n");

    /* Terminal restoration happens automatically via atexit(restore_terminal) */
}

/* ============================================================================
 * MAIN
 * ============================================================================ */

int main(void)
{
    volatile void *gpio_base;
    int key;

    /* ---- Print startup banner ---- */
    printf("\n");
    printf("============================================================\n");
    printf("  PARMCO Motor Control — L293D H-Bridge Driver\n");
    printf("  ECSE 4235 — Embedded Systems, Spring 2026\n");
    printf("  University of Georgia\n");
    printf("  Justin Moreno & Jalen Edusei\n");
    printf("============================================================\n");
    printf("\n");
    printf("  DRIVER:   L293D Dual H-Bridge Motor Driver IC\n");
    printf("  GPIO18  → L293D Enable (1,2EN)  [PWM speed control]\n");
    printf("  GPIO20  → L293D In1    (1A)     [direction bit A]\n");
    printf("  GPIO21  → L293D In2    (2A)     [direction bit B]\n");
    printf("  VCC1    → 5V   (logic supply)\n");
    printf("  VCC2    → 12V  (motor supply)\n");
    printf("\n");
    printf("  KEY BINDINGS:\n");
    printf("    w       Set direction to FORWARD (CW)  [In1=H, In2=L]\n");
    printf("    s       Set direction to REVERSE (CCW) [In1=L, In2=H]\n");
    printf("    + / =   Increase speed by 10%%\n");
    printf("    -       Decrease speed by 10%%\n");
    printf("    SPACE   Toggle motor ON / OFF\n");
    printf("    q       Quit program\n");
    printf("\n");
    printf("------------------------------------------------------------\n");
    printf("\n");

    /* ---- Install signal handlers ---- */
    signal(SIGINT,  signal_handler);
    signal(SIGTERM, signal_handler);

    /* ---- Initialize pigpio ----
     * gpioInitialise() must be called before any other pigpio function.
     * It maps the GPIO and DMA registers, configures the DMA channels,
     * and sets up the internal timing infrastructure.
     * Returns the pigpio version number on success, or PI_INIT_FAILED. */
    if (gpioInitialise() < 0) {
        fprintf(stderr, "[PARMCO] Failed to initialise pigpio.\n");
        fprintf(stderr, "Make sure you are running as root (sudo).\n");
        return EXIT_FAILURE;
    }
    printf("[PARMCO] pigpio initialised (version %d).\n", gpioVersion());

    /* ---- Map GPIO registers via /dev/gpiomem ----
     * This gives us a virtual pointer to the BCM2711 GPIO register block.
     * We pass this to our assembly module so it can directly manipulate
     * the GPFSEL, GPSET, and GPCLR registers. */
    gpio_base = map_gpio();
    printf("[PARMCO] GPIO registers mapped at virtual address %p.\n", gpio_base);

    /* ---- Initialize the assembly module ----
     * gpio_init() stores the base pointer in the assembly module's
     * .data section for use by gpio_set_output() and gpio_write(). */
    gpio_init(gpio_base);
    printf("[PARMCO] Assembly GPIO module initialised.\n");

    /* ---- Configure GPIO pins via assembly ----
     * Set GPIO20 (In1) and GPIO21 (In2) as outputs for direction control.
     * GPIO18 (Enable/PWM) is configured by pigpio internally — we don't
     * touch it with our assembly code to avoid conflicts. */
    gpio_set_output(PIN_IN1);
    printf("[PARMCO] GPIO%d configured as output (L293D In1).\n", PIN_IN1);

    gpio_set_output(PIN_IN2);
    printf("[PARMCO] GPIO%d configured as output (L293D In2).\n", PIN_IN2);

    /* === ORIGINAL AI CODE (CP2) — kept per course documentation rules ===
     * // gpio_set_output(PIN_DIR);
     * // printf("[PARMCO] GPIO%d configured as output (direction indicator).\n", PIN_DIR);
     * === END ORIGINAL AI CODE === */

    /* Set initial direction: forward (In1=HIGH, In2=LOW) */
    update_direction();
    printf("[PARMCO] Direction set to FORWARD (In1=HIGH, In2=LOW).\n");

    /* === ORIGINAL AI CODE (CP2) — kept per course documentation rules ===
     * // gpio_write(PIN_DIR, motor_direction);
     * === END ORIGINAL AI CODE === */

    /* Set initial PWM state: motor off, Enable duty = 0 */
    gpioPWM(PIN_ENABLE, 0);
    printf("[PARMCO] GPIO%d PWM initialised (Enable duty = 0).\n", PIN_ENABLE);

    /* ---- Switch terminal to raw mode ---- */
    set_raw_mode();

    printf("\n[PARMCO] Ready. Press keys to control the motor.\n\n");
    print_status();

    /* ==================================================================
     * MAIN CONTROL LOOP
     * ==================================================================
     * This loop runs at approximately 20 Hz (50ms delay per iteration).
     * On each iteration:
     *   1. Check if the quit flag was set by the signal handler.
     *   2. Poll the keyboard for a keypress (non-blocking via kbhit).
     *   3. If a key was pressed, process it and update state.
     *   4. Update the hardware outputs (L293D In1/In2 and Enable PWM).
     *   5. Sleep for 50ms to avoid spinning the CPU.
     */
    while (!quit_requested) {

        /* ---- Check for keyboard input ---- */
        if (kbhit()) {
            key = read_key();

            switch (key) {
                case 'w':
                case 'W':
                    /* Set direction to forward (clockwise).
                     * L293D: In1=HIGH, In2=LOW → current flows A→Motor→B.
                     * If already forward, the update_direction() call is
                     * idempotent — writing the same values to GPSET/GPCLR
                     * has no harmful effect. */
                    motor_direction = 1;
                    break;

                case 's':
                case 'S':
                    /* Set direction to reverse (counterclockwise).
                     * L293D: In1=LOW, In2=HIGH → current flows B→Motor→A.
                     *
                     * WARNING: Reversing direction at high speed subjects
                     * the motor to sudden polarity reversal. The L293D
                     * handles the electrical transition safely (built-in
                     * cross-conduction protection), but the mechanical
                     * stress on the motor shaft and any attached gearbox
                     * can be significant. For a production system, ramp
                     * speed to 0 before reversing. For this lab demo with
                     * a small motor, direct reversal is acceptable. */
                    motor_direction = 0;
                    break;

                case '+':
                case '=':
                    /* Increase speed by SPEED_STEP percent.
                     * Cap at 100% to prevent overflow. */
                    motor_speed += SPEED_STEP;
                    if (motor_speed > 100) motor_speed = 100;
                    break;

                case '-':
                case '_':
                    /* Decrease speed by SPEED_STEP percent.
                     * Floor at 0% to prevent negative values. */
                    motor_speed -= SPEED_STEP;
                    if (motor_speed < 0) motor_speed = 0;
                    break;

                case ' ':
                    /* Toggle motor on/off.
                     * The toggle is unconditional: pressing space always
                     * flips the state. When toggling OFF, the Enable PWM
                     * goes to 0 and the L293D outputs go high-impedance.
                     * When toggling ON, the Enable PWM resumes at the
                     * current speed setting. */
                    motor_running = !motor_running;
                    break;

                case 'q':
                case 'Q':
                    /* Quit the program cleanly. */
                    quit_requested = 1;
                    break;

                default:
                    /* Unknown key — ignore silently. */
                    break;
            }

            /* ---- Update hardware outputs after every keypress ---- */

            /* Update L293D direction pins (In1/In2) via assembly.
             * gpio_write() writes to GPSET0 or GPCLR0 atomically —
             * no read-modify-write race condition. */
            update_direction();

            /* === ORIGINAL AI CODE (CP2) — kept per course documentation rules ===
             * // gpio_write(PIN_DIR, motor_direction);
             * === END ORIGINAL AI CODE === */

            /* Update PWM duty cycle on Enable pin via pigpio.
             * gpioPWM() reconfigures the DMA waveform immediately. */
            update_pwm();

            /* Refresh the status display */
            print_status();
        }

        /* ---- Brief sleep to avoid CPU spin ----
         * 50ms gives ~20 iterations per second, which is more than fast
         * enough for human keyboard input. This keeps CPU usage near 0%. */
        usleep(LOOP_DELAY_US);
    }

    /* ---- Clean shutdown ---- */
    cleanup();

    return EXIT_SUCCESS;
}
