/**
 * PARMCOApp.swift
 * PARMCO — Phone APP RP4 Motor Control
 *
 * ECSE 4235 — Embedded Systems, Spring 2026
 * University of Georgia
 * Authors: Justin Moreno and Jalen Edusei
 *
 * AI Attribution:
 *   iOS port generated by Claude Opus 4.6 (Anthropic).
 *   Original React Native app by Justin Moreno and Jalen Edusei.
 */

import SwiftUI

@main
struct PARMCOApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
